src/objects/AR_Snapshot__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>AR Snapshots</relationshipLabel>
        <relationshipName>AR_Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>AR Snapshots</relationshipLabel>
        <relationshipName>AR_Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Paid_Amount__c</fullName>
        <label>Paid/Allocated Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>AR Snapshots</relationshipLabel>
        <relationshipName>AR_Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_0_30_Days__c</fullName>
        <label>0-30 Days</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_121_180_Days__c</fullName>
        <label>121-180 Days</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_180_Days__c</fullName>
        <label>&gt; 180 Days</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_31_60_Days__c</fullName>
        <label>31-60 Days</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_61_90_Days__c</fullName>
        <label>61-90 Days</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_91_120_Days__c</fullName>
        <label>91-120 Days</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount__c</fullName>
        <description>Unpaid amount of the invoice/Unallocated amount of the payment.</description>
        <inlineHelpText>Unpaid amount of the invoice/Unallocated amount of the payment.</inlineHelpText>
        <label>Unpaid/UnAllocated Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>AR Snapshot</label>
    <nameField>
        <label>AR Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AR Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <description>It is the sum of invoice lines amount excluding VAT/Tax</description>
        <inlineHelpText>It is the sum of invoice lines amount excluding VAT/Tax</inlineHelpText>
        <label>Subtotal</label>
        <summarizedField>Invoice_Line__c.Line_Amount__c</summarizedField>
        <summaryForeignKey>Invoice_Line__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Posted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Paid_Amount__c</fullName>
        <label>Paid Amount</label>
        <summarizedField>Payment_Allocation__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Payment_Allocation__c.Status__c</field>
            <operation>equals</operation>
            <value>Completed, Complete</value>
        </summaryFilterItems>
        <summaryForeignKey>Payment_Allocation__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_0_30_Days__c</fullName>
        <description>Unpaid Amount from the Invoice Date(0-30 days)</description>
        <formula>IF(No_Of_Days_From_Invoice_Date__c &lt;= 30, Unpaid_Amount__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Unpaid Amount from the Invoice Date(0-30 days)</inlineHelpText>
        <label>Unpaid Amount(0-30 Days)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_121_180_Days__c</fullName>
        <formula>IF(No_Of_Days_From_Invoice_Date__c &gt;= 121 &amp;&amp; No_Of_Days_From_Invoice_Date__c &lt;= 180, Unpaid_Amount__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unpaid Amount(121-180 Days)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_180_Days__c</fullName>
        <formula>IF(No_Of_Days_From_Invoice_Date__c &gt; 180, Unpaid_Amount__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unpaid Amount(&gt; 180 Days)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_31_60_Days__c</fullName>
        <formula>IF(No_Of_Days_From_Invoice_Date__c &gt;= 31 &amp;&amp; No_Of_Days_From_Invoice_Date__c &lt;= 60, Unpaid_Amount__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unpaid Amount(31-60 Days)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_61_90_Days__c</fullName>
        <formula>IF(No_Of_Days_From_Invoice_Date__c &gt;= 61 &amp;&amp; No_Of_Days_From_Invoice_Date__c &lt;= 90, Unpaid_Amount__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unpaid Amount(61-90 Days)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_91_120_Days__c</fullName>
        <formula>IF(No_Of_Days_From_Invoice_Date__c &gt;= 91 &amp;&amp; No_Of_Days_From_Invoice_Date__c &lt;= 120, Unpaid_Amount__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unpaid Amount(91-120 Days)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount__c</fullName>
        <formula>ROUND(Total_Invoice_Value__c, 2) - ROUND(Paid_Amount__c, 2) - ROUND( Credited_Amount__c, 2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unpaid Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Account/Customer who has made this Payment</description>
        <inlineHelpText>The Account/Customer who has made this Payment</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If this is selected on creation of Payment, allocation is done automatically</description>
        <inlineHelpText>If this is selected on creation of Payment, allocation is done automatically</inlineHelpText>
        <label>Invoice</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Invoice__c.Account__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initiated</fullName>
                    <color>#F3D904</color>
                    <label>Initiated</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <color>#78C953</color>
                    <default>true</default>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <color>#FF0000</color>
                    <label>Cancelled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UnAllocated_Amount_0_30_Days__c</fullName>
        <description>UnAllocated Amount from the Invoice Date(0-30 days)</description>
        <formula>IF(No_Of_Days_From_Payment_Date__c &lt;= 30, Unallocated_Amount__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UnAllocated Amount(0-30 Days)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UnAllocated_Amount_121_180_Days__c</fullName>
        <description>UnAllocated Amount from the Invoice Date(121-180 days)</description>
        <formula>IF(No_Of_Days_From_Payment_Date__c &gt;= 121 &amp;&amp; No_Of_Days_From_Payment_Date__c &lt;= 180, Unallocated_Amount__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>UnAllocated Amount from the Invoice Date(121-180 days)</inlineHelpText>
        <label>UnAllocated Amount(121-180 Days)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UnAllocated_Amount_180_Days__c</fullName>
        <description>UnAllocated Amount from the Invoice Date(&gt; 180 days)</description>
        <formula>IF(No_Of_Days_From_Payment_Date__c &gt; 180, Unallocated_Amount__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>UnAllocated Amount from the Invoice Date(&gt; 180 days)</inlineHelpText>
        <label>UnAllocated Amount(&gt; 180 Days)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UnAllocated_Amount_31_60_Days__c</fullName>
        <description>UnAllocated Amount from the Invoice Date(31-60 days)</description>
        <formula>IF(No_Of_Days_From_Payment_Date__c &gt;= 31 &amp;&amp; No_Of_Days_From_Payment_Date__c &lt;= 60, Unallocated_Amount__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>UnAllocated Amount from the Invoice Date(31-60 days)</inlineHelpText>
        <label>UnAllocated Amount(31-60 Days)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UnAllocated_Amount_61_90_Days__c</fullName>
        <description>UnAllocated Amount from the Invoice Date(31-60 days)</description>
        <formula>IF(No_Of_Days_From_Payment_Date__c &gt;= 61 &amp;&amp; No_Of_Days_From_Payment_Date__c &lt;= 90, Unallocated_Amount__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>UnAllocated Amount from the Invoice Date(31-60 days)</inlineHelpText>
        <label>UnAllocated Amount(61-90 Days)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UnAllocated_Amount_91_120_Days__c</fullName>
        <description>UnAllocated Amount from the Invoice Date(91-120 days)</description>
        <formula>IF(No_Of_Days_From_Payment_Date__c &gt;= 91 &amp;&amp; No_Of_Days_From_Payment_Date__c &lt;= 120, Unallocated_Amount__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>UnAllocated Amount from the Invoice Date(91-120 days)</inlineHelpText>
        <label>UnAllocated Amount(91-120 Days)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unallocated_Amount__c</fullName>
        <formula>IF( ISPICKVAL(Status__c, &apos;Cancelled&apos;), 0, Amount__c - Allocated_Amount__c - Refunded_Amount__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unallocated Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IITCustomerStatements.cls
global with sharing class IITCustomerStatements {

    
    public map<string, decimal> mapAmounts {get; set;}
    public list<InnerClassToDisplay> listofInnerclass {get; set;}
    InnerClassToDisplay innerClassToDisplay;
    
    public IITCustomerStatements(ApexPages.StandardController stdController) {
        
        list<AggregateResult> invoiceAggResult;
        list<AggregateResult> paymentAggResult;
        listofInnerclass  = new list<InnerClassToDisplay>();
        mapAmounts = new map<string, decimal>{'0-30'=> 0.00, '31-60'=> 0.00, '61-90' => 0.00, '91-120'=> 0.00, '121-180'=> 0.00, '>181' => 0.00};
        
        Id accountId = (Id) stdcontroller.getId();
        invoiceAggResult = [SELECT Sum(Unpaid_Amount_0_30_Days__c) sum1, Sum(Unpaid_Amount_31_60_Days__c) second, Sum(Unpaid_Amount_61_90_Days__c) third,
                            Sum(Unpaid_Amount_91_120_Days__c) forth, Sum(Unpaid_Amount_121_180_Days__c) fifth, Sum(Unpaid_Amount_180_Days__c) sixth
                            FROM Invoice__c
                            WHERE Invoice_Status__c = 'Posted'
                            AND 
                            Unpaid_Amount__c != 0
                            AND 
                            Invoice_Date__c <=: system.today()
                            AND
                            Account__c =: accountId
                            Group By Account__c
                            ];
    
        paymentAggResult = [SELECT Sum(UnAllocated_Amount_0_30_Days__c) sum1, Sum(UnAllocated_Amount_31_60_Days__c) second, Sum(UnAllocated_Amount_61_90_Days__c) third,
                            Sum(UnAllocated_Amount_91_120_Days__c) forth, Sum(UnAllocated_Amount_121_180_Days__c) fifth, Sum(UnAllocated_Amount_180_Days__c) sixth
                            FROM Payment__c
                            WHERE Status__c = 'Completed'
                             AND 
                             Unallocated_Amount__c != 0
                             AND 
                             Payment_Date__c <=: system.today()
                             AND
                             Account__c =: accountId
                             Group By Account__c
                            ];
        
        if(invoiceAggResult.size() > 0) {
            mapAmounts.put('0-30', ((decimal) invoiceAggResult[0].get('sum1')).setscale(2));
            mapAmounts.put('31-60', ((decimal) invoiceAggResult[0].get('second')).setscale(2));
            mapAmounts.put('61-90', ((decimal) invoiceAggResult[0].get('third')).setscale(2));
            mapAmounts.put('91-120', ((decimal) invoiceAggResult[0].get('forth')).setscale(2));
            mapAmounts.put('121-180', ((decimal) invoiceAggResult[0].get('fifth')).setscale(2));
            mapAmounts.put('>181', ((decimal) invoiceAggResult[0].get('sixth')).setscale(2));
        }
       
         if(paymentAggResult.size() > 0) {
            mapAmounts.put('0-30', (mapAmounts.get('0-30') - (decimal) paymentAggResult[0].get('sum1')).setscale(2));
            mapAmounts.put('31-60', (mapAmounts.get('31-60') - (decimal) paymentAggResult[0].get('second')).setscale(2));
            mapAmounts.put('61-90', (mapAmounts.get('61-90') - (decimal) paymentAggResult[0].get('third')).setscale(2));
            mapAmounts.put('91-120', (mapAmounts.get('91-120') - (decimal) paymentAggResult[0].get('forth')).setscale(2));
            mapAmounts.put('121-180', (mapAmounts.get('121-180') - (decimal) paymentAggResult[0].get('fifth')).setscale(2));
            mapAmounts.put('>181', (mapAmounts.get('>181') - (decimal) paymentAggResult[0].get('sixth')).setscale(2));
        }
        
        decimal sum = 0;
        for(string key : mapAmounts.keySet()) {
            innerClassToDisplay =  new InnerClassToDisplay();
            innerClassToDisplay.sRange = key;
            innerClassToDisplay.dValue = mapAmounts.get(key);
            listofInnerclass.add(innerClassToDisplay);
            sum = sum + mapAmounts.get(key);
        }
        innerClassToDisplay =  new InnerClassToDisplay(); 
        innerClassToDisplay.sRange = 'Total Due';
        innerClassToDisplay.dValue = sum;
        listofInnerclass.add(innerClassToDisplay);
    }
    
    public class InnerClassToDisplay
    {
        public String sRange {get; set;}
        public decimal dValue {get; set;}
        
        public InnerClassToDisplay()
        {
            sRange = '';
            dValue = 0.00;
        }
    }
    
    @RemoteAction
    global static ResponseClass generateRealTimeStatement(string accountId) {
        list<Invoice__c> unpaidInvoices;
        list<Payment__c> unAllocatedPayments;
        list<AR_Snapshot__c> snapshotRecordsToInsert = new list<AR_Snapshot__c>();
        string arRecordName;
        date todaysDate = system.today();
        ResponseClass responseClass = new ResponseClass();
        try {
                arRecordName = string.ValueOf(system.now());
                unpaidInvoices = [SELECT Invoice_Date__c,
                                  Account__c, Paid_Amount__c,Total_Invoice_Value__c,Unpaid_Amount__c,Unpaid_Amount_0_30_Days__c,Unpaid_Amount_31_60_Days__c,Unpaid_Amount_61_90_Days__c,Unpaid_Amount_91_120_Days__c,Unpaid_Amount_121_180_Days__c,Unpaid_Amount_180_Days__c
                                  FROM Invoice__c
                                  WHERE Invoice_Status__c = 'Posted'
                                  AND 
                                  Unpaid_Amount__c != 0
                                  AND 
                                  Invoice_Date__c <=: todaysDate
                                  AND
                                  Account__c =: accountId
                                ];

                unAllocatedPayments = [SELECT Account__c, Allocated_Amount__c, Amount__c,Payment_Date__c,Status__c, Unallocated_Amount__c, UnAllocated_Amount_180_Days__c, UnAllocated_Amount_0_30_Days__c, UnAllocated_Amount_121_180_Days__c, UnAllocated_Amount_31_60_Days__c, UnAllocated_Amount_61_90_Days__c, UnAllocated_Amount_91_120_Days__c
                                         FROM Payment__c
                                         WHERE Status__c = 'Completed'
                                         AND 
                                         Unallocated_Amount__c != 0
                                         AND 
                                         Payment_Date__c <=: todaysDate
                                         AND
                                         Account__c =: accountId
                                        ];

                // get the UnPaidInvoices
                snapshotRecordsToInsert = IITARUtilClass.populateARUnpaidInvoices(unpaidInvoices, arRecordName, system.today()); 
                
                // get the UnAllocatedPayments
                snapshotRecordsToInsert.addALL(IITARUtilClass.populateARUnAllocatedPayments(unAllocatedPayments, arRecordName, system.today()));
                
                // insert the data invoices and payments
                insert snapshotRecordsToInsert;
                responseClass.message = 'success';
                responseClass.snapshotName = arRecordName;
                return responseClass;
            } catch(exception ex) {
                system.debug('exception getMessage is : ' + ex.getTypeName() + ':'+ex.getMessage() + ':' + ex.getLineNumber() + ':' + ex.getStackTraceString() );
                
                responseClass.message = 'An exception has occured, exception type is ' + ex.getTypeName() + ':'+ex.getMessage() + ':' + ex.getLineNumber() + ':' + ex.getStackTraceString();
                return responseClass;
        } 
    }
    
    @RemoteAction
    global static ResponseClass generateHistoricStatement(string accountId, string snapshotName) {
        list<AR_Snapshot__c> snapshot = [SELECT Id FROM AR_Snapshot__c WHERE Name =: snapshotName AND Account__c =: accountId];
        ResponseClass responseClass = new ResponseClass();

        if(snapshot.size() > 0) {
            responseClass.message = 'success';
        } else {
            responseClass.message = 'No Snapshot records found ';
        }
        system.debug('snapshotName ' + snapshotName);

        return responseClass;
    }

    // global class used as reponse for JS
    global class ResponseClass {
        global string message;
        global string snapshotName;
    }
}