src/objects/AR_Snapshot__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>AR Snapshots</relationshipLabel>
        <relationshipName>AR_Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deferred_Revenue_Balance__c</fullName>
        <label>Deferred Revenue Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>AR Snapshots</relationshipLabel>
        <relationshipName>AR_Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Paid_Amount__c</fullName>
        <label>Paid/Allocated Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>AR Snapshots</relationshipLabel>
        <relationshipName>AR_Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Statement_Date__c</fullName>
        <description>This is will be populated when you generate the Statement using the UI.</description>
        <label>Statement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Value__c</fullName>
        <description>Total Invoice Value or Payment Amount</description>
        <inlineHelpText>Total Invoice Value or Payment Amount</inlineHelpText>
        <label>Transaction Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_0_30_Days__c</fullName>
        <label>0-30 Days</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_121_180_Days__c</fullName>
        <label>121-180 Days</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_180_Days__c</fullName>
        <label>&gt; 180 Days</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_31_60_Days__c</fullName>
        <label>31-60 Days</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_61_90_Days__c</fullName>
        <label>61-90 Days</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_91_120_Days__c</fullName>
        <label>91-120 Days</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount__c</fullName>
        <description>Unpaid amount of the invoice/Unallocated amount of the payment.</description>
        <inlineHelpText>Unpaid amount of the invoice/Unallocated amount of the payment.</inlineHelpText>
        <label>Unpaid/UnAllocated Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>AR Snapshot</label>
    <nameField>
        <label>AR Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AR Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <description>It is the sum of invoice lines amount excluding VAT/Tax</description>
        <inlineHelpText>It is the sum of invoice lines amount excluding VAT/Tax</inlineHelpText>
        <label>Subtotal</label>
        <summarizedField>Invoice_Line__c.Line_Amount__c</summarizedField>
        <summaryForeignKey>Invoice_Line__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Paid_Amount__c</fullName>
        <label>Paid Amount</label>
        <summarizedField>Payment_Allocation__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Payment_Allocation__c.Status__c</field>
            <operation>equals</operation>
            <value>Completed, Complete</value>
        </summaryFilterItems>
        <summaryForeignKey>Payment_Allocation__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Invoice_Value__c</fullName>
        <description>Subtotal - Discount + VAT + Tax</description>
        <formula>Amount__c - Discount_Value__c + VAT__c + Tax__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Subtotal - Discount + VAT + Tax</inlineHelpText>
        <label>Total Invoice Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_0_30_Days__c</fullName>
        <description>Unpaid Amount from the Invoice Date(0-30 days)</description>
        <formula>IF(No_Of_Days_From_Invoice_Date__c &lt;= 30, Unpaid_Amount__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Unpaid Amount from the Invoice Date(0-30 days)</inlineHelpText>
        <label>Unpaid Amount(0-30 Days)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_121_180_Days__c</fullName>
        <formula>IF(No_Of_Days_From_Invoice_Date__c &gt;= 121 &amp;&amp; No_Of_Days_From_Invoice_Date__c &lt;= 180, Unpaid_Amount__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unpaid Amount(121-180 Days)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_180_Days__c</fullName>
        <formula>IF(No_Of_Days_From_Invoice_Date__c &gt; 180, Unpaid_Amount__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unpaid Amount(&gt; 180 Days)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_31_60_Days__c</fullName>
        <formula>IF(No_Of_Days_From_Invoice_Date__c &gt;= 31 &amp;&amp; No_Of_Days_From_Invoice_Date__c &lt;= 60, Unpaid_Amount__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unpaid Amount(31-60 Days)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_61_90_Days__c</fullName>
        <formula>IF(No_Of_Days_From_Invoice_Date__c &gt;= 61 &amp;&amp; No_Of_Days_From_Invoice_Date__c &lt;= 90, Unpaid_Amount__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unpaid Amount(61-90 Days)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount_91_120_Days__c</fullName>
        <formula>IF(No_Of_Days_From_Invoice_Date__c &gt;= 91 &amp;&amp; No_Of_Days_From_Invoice_Date__c &lt;= 120, Unpaid_Amount__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unpaid Amount(91-120 Days)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unpaid_Amount__c</fullName>
        <formula>ROUND(Total_Invoice_Value__c, 2) - ROUND(Paid_Amount__c, 2) - ROUND( Credited_Amount__c, 2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unpaid Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Account/Customer who has made this Payment</description>
        <inlineHelpText>The Account/Customer who has made this Payment</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Allocated_Amount__c</fullName>
        <description>The Amount that has already been Allocated.</description>
        <inlineHelpText>The Amount that has already been Allocated.</inlineHelpText>
        <label>Allocated Amount</label>
        <summarizedField>Payment_Allocation__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Payment_Allocation__c.Status__c</field>
            <operation>equals</operation>
            <value>Completed</value>
        </summaryFilterItems>
        <summaryForeignKey>Payment_Allocation__c.Payment__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If this is selected on creation of Payment, allocation is done automatically</description>
        <inlineHelpText>If this is selected on creation of Payment, allocation is done automatically</inlineHelpText>
        <label>Invoice</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Invoice__c.Account__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>The Date on which this Payment was made.</description>
        <inlineHelpText>The Date on which this Payment was made.</inlineHelpText>
        <label>Payment Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unallocated_Amount__c</fullName>
        <formula>IF( ISPICKVAL(Status__c, &apos;Cancelled&apos;), 0, Amount__c - Allocated_Amount__c - Refunded_Amount__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unallocated Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Revenue_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>The account record against which the transaction is recorded</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Revenue Transactions</relationshipLabel>
        <relationshipName>Revenue_Transaction_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Deferred_Balance__c</fullName>
        <description>The deferred balance as of this accounting period</description>
        <label>Deferred Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The invoice against which this transaction is recorded</description>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Revenue Transactions</relationshipLabel>
        <relationshipName>Revenue_Transaction_Invoice</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Revenue Transaction</label>
    <nameField>
        <label>Revenue Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IITARUtilClass.cls
public with sharing class IITARUtilClass {
	public static list<AR_Snapshot__c> populateARUnpaidInvoices(list<Invoice__c> unpaidInvoices, string nameOfAR, date closingDate) {

		list<AR_Snapshot__c> snapshotRecordsToInsert = new list<AR_Snapshot__c>();	
		AR_Snapshot__c snapshot;

		for(Invoice__c unpaidInvoice : unpaidInvoices) {

			integer NoOfDaysfromInvoiceDateToClosingDate = unpaidInvoice.Invoice_Date__c.daysBetween(closingDate);

	        snapshot = new AR_Snapshot__c();
	        snapshot.Unpaid_Amount_180_Days__c = 0;
	        snapshot.Unpaid_Amount_0_30_Days__c = 0;
	        snapshot.Unpaid_Amount_121_180_Days__c = 0;
	        snapshot.Unpaid_Amount_31_60_Days__c = 0;
	        snapshot.Unpaid_Amount_61_90_Days__c = 0;
	        snapshot.Unpaid_Amount_91_120_Days__c = 0;

	        if(NoOfDaysfromInvoiceDateToClosingDate >= 0 && NoOfDaysfromInvoiceDateToClosingDate <= 30) {
	        	snapshot.Unpaid_Amount_0_30_Days__c = unpaidInvoice.Unpaid_Amount__c;
	        } else if(NoOfDaysfromInvoiceDateToClosingDate >= 31 && NoOfDaysfromInvoiceDateToClosingDate <= 60) {
	        	snapshot.Unpaid_Amount_31_60_Days__c = unpaidInvoice.Unpaid_Amount__c;
			} else if(NoOfDaysfromInvoiceDateToClosingDate >= 61 && NoOfDaysfromInvoiceDateToClosingDate <= 90) {
	        	snapshot.Unpaid_Amount_61_90_Days__c = unpaidInvoice.Unpaid_Amount__c;
	        } else if(NoOfDaysfromInvoiceDateToClosingDate >= 91 && NoOfDaysfromInvoiceDateToClosingDate <= 120) {
	        	snapshot.Unpaid_Amount_91_120_Days__c = unpaidInvoice.Unpaid_Amount__c;
	        } else if(NoOfDaysfromInvoiceDateToClosingDate >= 121 && NoOfDaysfromInvoiceDateToClosingDate <= 180) {
	        	 snapshot.Unpaid_Amount_121_180_Days__c = unpaidInvoice.Unpaid_Amount__c;
	        } else if(NoOfDaysfromInvoiceDateToClosingDate >= 181) {
	        	 snapshot.Unpaid_Amount_180_Days__c = unpaidInvoice.Unpaid_Amount__c;
	        } 

	        snapshot.Name = nameOfAR;
	        snapshot.Invoice__c = unpaidInvoice.Id;
	        snapshot.Paid_Amount__c = unpaidInvoice.Paid_Amount__c;
	        snapshot.Unpaid_Amount__c = unpaidInvoice.Unpaid_Amount__c;
	        snapshot.Transaction_Value__c = unpaidInvoice.Total_Invoice_Value__c;
	        snapshot.Transaction_Type__c = 'Invoice'; 
	        snapshot.Account__c = unpaidInvoice.Account__c;
	        snapshot.Deferred_Revenue_Balance__c = 0;
	        snapshot.Statement_Date__c = closingDate;
	        
	        if(unpaidInvoice.Revenue_Transaction_Invoice__r.size() > 0) {
	            for(Revenue_Transaction__c revTrans : unpaidInvoice.Revenue_Transaction_Invoice__r) {
	                snapshot.Deferred_Revenue_Balance__c = snapshot.Deferred_Revenue_Balance__c + revTrans.Deferred_Balance__c;
	            }
	        }
	        
	        snapshotRecordsToInsert.add(snapshot);
	    }

	    return snapshotRecordsToInsert;
	}


	public static list<AR_Snapshot__c> populateARUnAllocatedPayments(list<Payment__c> unAllocatedPayments, string nameOfAR, date closingDate) {
		list<AR_Snapshot__c> snapshotRecordsToInsert = new list<AR_Snapshot__c>();	
		AR_Snapshot__c snapshot;

		for(Payment__c payment : unAllocatedPayments) {
            integer NoOfDaysfromInvoiceDateToClosingDate = payment.Payment_Date__c.daysBetween(closingDate);

            snapshot = new AR_Snapshot__c();
            snapshot.Unpaid_Amount_180_Days__c = 0;
            snapshot.Unpaid_Amount_0_30_Days__c = 0;
            snapshot.Unpaid_Amount_121_180_Days__c = 0;
            snapshot.Unpaid_Amount_31_60_Days__c = 0;
            snapshot.Unpaid_Amount_61_90_Days__c = 0;
            snapshot.Unpaid_Amount_91_120_Days__c = 0;

            if(NoOfDaysfromInvoiceDateToClosingDate >= 0 && NoOfDaysfromInvoiceDateToClosingDate <= 30) {
	        	snapshot.Unpaid_Amount_0_30_Days__c = payment.Unallocated_Amount__c * (-1);
	        } else if(NoOfDaysfromInvoiceDateToClosingDate >= 31 && NoOfDaysfromInvoiceDateToClosingDate <= 60) {
	        	snapshot.Unpaid_Amount_31_60_Days__c = payment.Unallocated_Amount__c * (-1);
			} else if(NoOfDaysfromInvoiceDateToClosingDate >= 61 && NoOfDaysfromInvoiceDateToClosingDate <= 90) {
	        	snapshot.Unpaid_Amount_61_90_Days__c = payment.Unallocated_Amount__c * (-1);
	        } else if(NoOfDaysfromInvoiceDateToClosingDate >= 91 && NoOfDaysfromInvoiceDateToClosingDate <= 120) {
	        	snapshot.Unpaid_Amount_91_120_Days__c = payment.Unallocated_Amount__c * (-1);
	        } else if(NoOfDaysfromInvoiceDateToClosingDate >= 121 && NoOfDaysfromInvoiceDateToClosingDate <= 180) {
	        	 snapshot.Unpaid_Amount_121_180_Days__c = payment.Unallocated_Amount__c * (-1);
	        } else if(NoOfDaysfromInvoiceDateToClosingDate >= 181) {
	        	 snapshot.Unpaid_Amount_180_Days__c = payment.Unallocated_Amount__c * (-1);
	        } 

            snapshot.Name = nameOfAR;
            snapshot.Payment__c = payment.Id;
            snapshot.Paid_Amount__c = payment.Allocated_Amount__c * (-1);
            snapshot.Unpaid_Amount__c = payment.Unallocated_Amount__c * (-1);
            snapshot.Transaction_Value__c = payment.Amount__c * (-1);
            snapshot.Transaction_Type__c = 'Payment'; 
            snapshot.Account__c = payment.Account__c;
            snapshot.Statement_Date__c = closingDate;
            
            snapshotRecordsToInsert.add(snapshot);
        }

        return snapshotRecordsToInsert;
	}
}