src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Removed__c</fullName>
        <label>Date Removed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Installed_By__c</fullName>
        <label>Installed By</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Description__c</fullName>
        <label>Item Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VTMig_AssetHierarchyController.cls
/**
 * Created by triciaigoe on 2019-12-13.
 */

public without sharing class VTMig_AssetHierarchyController { 

    /*
    Method to get the List of Asset Hierarchy records passing any Asset of the Hierarchy structure.
    */
    @AuraEnabled
    public static List<Asset> getAssetHierarchy(string assetId) {
        try{
            Asset theRootAsset = [SELECT RootAssetId FROM Asset WHERE ID =: assetId];
            String rootAssetId;
            if(theRootAsset.RootAssetId == null){
                rootAssetId = assetId;
            }else{
                rootAssetId = theRootAsset.RootAssetId;
            }
            List<Asset> assetHierarchy = [SELECT id, Name, Product2.Name, ParentId, AccountID, Date_Removed__c,
                    InstallDate,Installed_By__c,
                    RootAssetId,RootAsset.Name,
                    RootAsset.Product2.Name, Item_Description__c,Account_Name__c,
                    Item__c,
                    Asset.Product2.ProductCode
            FROM Asset
            WHERE RootAssetId =: rootAssetId OR ID =: rootAssetId];
            return assetHierarchy;
        }catch(Exception ex){
            throw new AuraHandledException(ex.getMessage() + ' ' +ex.getLineNumber());
        }

    }

}