src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Removed__c</fullName>
        <label>Date Removed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Installed_By__c</fullName>
        <label>Installed By</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Description__c</fullName>
        <label>Item Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence_No__c</fullName>
        <description>This field is used by the BaaN --&gt; Salesforce integration program, as well as when Assets are entered directly into SF. It&apos;s primary function is to serve as a sorting mechanism. Sequence No is typically incremented by 10 to allow for Assets to be inserted in-between.</description>
        <label>Sequence No</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AssetHirerachy_Controller.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
*  controller class for AssetHirerachy to show the asset hirerachy in lightning component by using
*  lighting tree
*
* Additional information about this class, multiple lines
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Jitendra Rawat   jrawat@kvh.com
* @repository     https://bitbucket.org/kvhdev/asset-hierarchy/src/master/
*/
public class AssetHirerachy_Controller {
    /*
    Method to get the List of Asset Hierarchy records passing any Asset of the Hierarchy structure.
    */
    @AuraEnabled
    public static List<Asset> getAssetHierarchy(string assetId) {
        try{
            Asset theRootAsset = [SELECT RootAssetId FROM Asset WHERE ID =: assetId];
            String rootAssetId;
            if(theRootAsset.RootAssetId == null){
                rootAssetId = assetId;
            }else{
                rootAssetId = theRootAsset.RootAssetId;
            }
            List<Asset> assetHierarchy = [SELECT id, Name, Product2.Name, ParentId, AccountID, Date_Removed__c,
                                          InstallDate,Sequence_No__c,Installed_By__c,
                                          RootAssetId,RootAsset.Name,
                                          RootAsset.Product2.Name, Item_Description__c,Account_Name__c,
                                          Item__c,
                                          Asset.Product2.ProductCode
                                          FROM Asset 
                                          WHERE RootAssetId =: rootAssetId OR ID =: rootAssetId];      
            return assetHierarchy;
        }catch(Exception ex){
           throw new AuraHandledException(ex.getMessage() + ' ' +ex.getLineNumber());
        }
      
    }    
}