src/objects/Batch_Job__c.object
<CustomObject>
    <description>This holds the records for batch process of MRR and Renew Orders</description>
    <fields>
        <fullName>Completed_Date_and_Time__c</fullName>
        <label>Completed Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Exception_Log__c</fullName>
        <label>Exception Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date_and_Time__c</fullName>
        <label>Start Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Completed with errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MRR Calculation</fullName>
                </value>
                <value>
                    <fullName>Auto Renewals</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SteelBrick Batch Jobs</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice IT Batch Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>BMS_Contract_Year__c</fullName>
        <inlineHelpText>This is the year of the actual contract for billing purposes. We will need to use to initially calculate the Billing Amount</inlineHelpText>
        <label>BMS Contract Year</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Value__c</fullName>
        <inlineHelpText>Discount offered on this order</inlineHelpText>
        <label>Discount Value</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exception_Log__c</fullName>
        <label>Exception Log</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Net_Total__c</fullName>
        <inlineHelpText>Subtotal - Discount Value</inlineHelpText>
        <label>Net Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_End_Date__c</fullName>
        <label>Service End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Awaiting Customer Signature</fullName>
                </value>
                <value>
                    <fullName>Ready for Admin Processing</fullName>
                </value>
                <value>
                    <fullName>Administration in Progress</fullName>
                </value>
                <value>
                    <fullName>Order Entry Complete</fullName>
                </value>
                <value>
                    <fullName>Ready for Fulfillment</fullName>
                </value>
                <value>
                    <fullName>In Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Ready for Dispatch</fullName>
                </value>
                <value>
                    <fullName>In Service</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Registration</fullName>
                </value>
                <value>
                    <fullName>Enrollment</fullName>
                </value>
                <value>
                    <fullName>Awaiting Documents</fullName>
                </value>
                <value>
                    <fullName>Documents Recieved</fullName>
                </value>
                <value>
                    <fullName>Documents sent for Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment Passed</fullName>
                </value>
                <value>
                    <fullName>Certificate Dispatched</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Awaiting Return</fullName>
                </value>
                <value>
                    <fullName>On boarding in progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order (InvoiceIT) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Job_Rate_Plan_Charge__c.object
<CustomObject>
    <fields>
        <fullName>AnnualRentYear2__c</fullName>
        <label>RentYear2(Migration)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AnnualRentYear3__c</fullName>
        <label>RentYear3(Migration)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AnnualRentYear4__c</fullName>
        <label>RentYear4(Migration)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BMS_Contract_Year__c</fullName>
        <label>BMS Contract Year</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Value__c</fullName>
        <inlineHelpText>The discount value that has been applied to the order charge.</inlineHelpText>
        <label>Discount Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Uplift_Date__c</fullName>
        <label>Last Uplift Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legacy_Orders__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Legacy Orders?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Net_Total__c</fullName>
        <inlineHelpText>Shows the Net Total for the order charge which is calculated by subtracting the Discount Value from the Sub Total. (Sub Total - Discount Value)</inlineHelpText>
        <label>Net Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Next_Uplift_Date__c</fullName>
        <inlineHelpText>Date when the uplift will happen.</inlineHelpText>
        <label>Next Uplift Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Shows the order record that the charge is related to - click to be taken directly to the order</inlineHelpText>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Order_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_Format__c</fullName>
        <label>Pricing Model</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pricing_Model</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price_Type__c</fullName>
        <inlineHelpText>The frequency at which the charge will be billed (One Time, Monthly, Quarterly, Annual etc)</inlineHelpText>
        <label>Price Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One Time</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Half Yearly</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Usage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <inlineHelpText>Shows the Sub Total for the order charge which is calculated by multiplying the unit price by the quantity being ordered. (Quantity * Unit Price)</inlineHelpText>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>The quantity of products/services being sold</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_End_Date__c</fullName>
        <label>Service End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Shows the status of the order charge. The status field can be used to control whether the order line should be invoiced or provisioned for example.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready to Bill</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Awaiting Customer Signature</fullName>
                </value>
                <value>
                    <fullName>Ready for Admin Processing</fullName>
                </value>
                <value>
                    <fullName>Administration in Progress</fullName>
                </value>
                <value>
                    <fullName>Awaiting Return</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Price_2nd_Year__c</fullName>
        <formula>(Uplift__c * Unit_Price_1st_Year__c) + Unit_Price_1st_Year__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit Price (2nd Year)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price_3rd_Year__c</fullName>
        <formula>(Uplift__c * Unit_Price_2nd_Year__c) + Unit_Price_2nd_Year__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit Price (3rd Year)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price_4th_Year__c</fullName>
        <formula>(Uplift__c * Unit_Price_3rd_Year__c) + Unit_Price_3rd_Year__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit Price (4th Year)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <inlineHelpText>The unit selling price of the order line</inlineHelpText>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Uplift_Frequency__c</fullName>
        <label>Uplift Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Half Yearly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Uplift__c</fullName>
        <label>Uplift %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Order Rate Plan Charge</label>
    <nameField>
        <label>Order Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VTMig_BatchUpliftPrice.cls
/**
 * Created by triciaigoe on 2019-11-27.
 */

global without sharing class VTMig_BatchUpliftPrice implements Database.Batchable<sObject>,Database.Stateful{

    global String query;
    global set<Id> orderIds;
    Date dateToday = system.today();
    Batch_Job__c batchJob;
    global string errorLog = null;
    string currentBatchDetails = '';
    global Id chargeId = 'a20190000008yP9';

    global VTMig_BatchUpliftPrice(String query, boolean useInternalQuery) {
        this.query = query;
        orderIds = new set<Id>();

        if(useInternalQuery == true || useInternalQuery == null) {
            this.query = 'SELECT BMS_Contract_Year__c, AnnualRentYear2__c, AnnualRentYear3__c, AnnualRentYear4__c, Net_Total__c, ' +
                    'Unit_Price_2nd_Year__c, Unit_Price_3rd_Year__c, Unit_Price_4th_Year__c, Quantity__c, Discount_Value__c, ' +
                    'Uplift__c, Uplift_Frequency__c, Price_Type__c,Order__c, Legacy_Orders__c, Next_Uplift_Date__c, ' +
                    'Unit_Price__c, Order__r.BMS_Contract_Year__c FROM Job_Rate_Plan_Charge__c ' +
                    'WHERE (Uplift__c > 0 OR Legacy_Orders__c = true) ' +
                    'AND (Service_End_Date__c = null ' +
                    'OR Service_End_Date__c >=:dateToday) ' +
                    'AND Next_Uplift_Date__c!= null ' +
                    'AND Next_Uplift_Date__c <=:dateToday';
        } else {
            this.query = query;
        }

        batchJob = new Batch_Job__c(Name = 'BatchUpliftPrice - ' + system.today(), Type__c = 'BatchUpliftPrice', Start_Date_and_Time__c = system.now(), Status__c = 'Processing');
        insert batchJob;
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<sObject> scope) {
        SavePoint sp;
        try {
            list<Job_Rate_Plan_Charge__c> charges = scope;
            list<Job__c> ordersToUpdate = new list<Job__c>();

            currentBatchDetails = '\n' + '\n' + '\n';
            for(Job_Rate_Plan_Charge__c charge : charges) {
                currentBatchDetails = currentBatchDetails + charge.Id + '\n';
            }

            sp = DataBase.SetSavePoint();
            for(Job_Rate_Plan_Charge__c charge : charges) {
                decimal newPrice = null;
                // check if its a legacy charge
                if(charge.Legacy_Orders__c) {
                    if(charge.BMS_Contract_Year__c != null) {
                        ++charge.BMS_Contract_Year__c;

                        // just assgin the unit price, in case if the annualrentyr is null then we will use the unit price
                        newPrice = charge.Unit_Price__c;
                        if(charge.BMS_Contract_Year__c == 2) {
                            if(charge.AnnualRentYear2__c != null)
                                newPrice = charge.AnnualRentYear2__c;
                        } else if(charge.BMS_Contract_Year__c == 3) {
                            if(charge.AnnualRentYear3__c != null)
                                newPrice = charge.AnnualRentYear3__c;
                        } else if(charge.AnnualRentYear4__c != null) {
                            newPrice = charge.AnnualRentYear4__c;
                        }
                    }
                } else {
                    if(charge.Uplift__c == null)
                        charge.Uplift__c = 0;

                    if(charge.Unit_Price__c != null) {
                        newPrice = (charge.Unit_Price__c * (charge.Uplift__c/100)) + charge.Unit_Price__c;
                    }
                }

                if(newPrice != null) {
                    // update the price
                    charge.Unit_Price__c = newPrice;
                    charge.Price__c = charge.Quantity__c * charge.Unit_Price__c;
                    charge.Net_Total__c = charge.Price__c - charge.Discount_Value__c;

                    system.debug('Next_Uplift_Date__c is ' + charge.Next_Uplift_Date__c);

                    // populate the next uplift date
                    charge.Last_Uplift_Date__c = charge.Next_Uplift_Date__c;
                    charge.Next_Uplift_Date__c = charge.Next_Uplift_Date__c.addMonths(12);
                    charge.Price_Format__c = 'Default';
                    charge.BMS_Contract_Year__c = charge.BMS_Contract_Year__c;

                    system.debug('Id is ' +charge.Id+ 'Next date' +charge.Next_Uplift_Date__c);
                    system.debug('New Price is ' + charge.Unit_Price__c);

                    if(!orderIds.contains(charge.Order__c)) {
                        orderIds.add(charge.Order__c);

                        /*if(charge.Legacy_Orders__c) {
                            ordersToUpdate.add(new Job__c(Id = charge.Order__c));
                        }*/
                    }
                }
            }

            // unit price will be updated
            update charges;

            // we need to update the contract terms for legacy data
            //update ordersToUpdate;

            currentBatchDetails = '';
        } catch(exception ex) {
            system.debug('exception getMessage is : ' + ex.getTypeName() + ':'+ex.getMessage() + ':' + ex.getLineNumber() + ':' + ex.getStackTraceString() );
            database.rollback(sp);

            errorLog += '\n' + 'An exception has occured, exception type is ' + ex.getTypeName() + ':'+ex.getMessage() + ':' + ex.getLineNumber() + ':' + ex.getStackTraceString() + '\n';
            errorLog += ': ' + currentBatchDetails;
        }
    }

    global void finish(Database.BatchableContext BC) {

        batchJob.Completed_Date_and_Time__c = system.now();
        if(errorLog == null) {
            batchJob.Status__c = 'Completed';
        } else {
            batchJob.Status__c = 'Completed with Errors';

            if(errorLog.Length() < 32768) {
                batchJob.Exception_Log__c = errorLog;
            } else {
                Attachment attachment = new Attachment();
                attachment.Body = Blob.valueOf(errorLog);
                attachment.Name = 'ErrorLog.txt';
                attachment.ParentId = batchJob.Id;
                insert attachment;

                batchJob.Exception_Log__c = 'Error log is attached and the same can be found attachement releated list';
            }
        }
        update batchJob;


        if(!Test.isRunningTest()) {
            VTMig_IITBatchProcessForRecalculateOrder batchProcessForRecalculateOrder = new VTMig_IITBatchProcessForRecalculateOrder(orderIds);
            Database.executeBatch(batchProcessForRecalculateOrder,1);
        }
    }

}