src/objects/Contract_Addendum__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Contract Addendums</relationshipLabel>
        <relationshipName>Contract_Addendums</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Addendum</label>
    <nameField>
        <displayFormat>Add-{00000}</displayFormat>
        <label>Contract Add Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Addendums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order (InvoiceIT) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VTMig_AttachmentTriggerHandler_Test.cls
/**
 * Created by triciaigoe on 2020-01-02.
 */
@IsTest
public with sharing class VTMig_AttachmentTriggerHandler_Test {

    @IsTest
    public static void testAttachment(){

        Account acc = VTMig_TestUtilities.createKVCustomer();
        insert acc;

        Job__c order = VTMig_TestUtilities.createMasterOrder(acc.Id);
        insert order;

        Contract_Addendum__c contractAddendum = new Contract_Addendum__c();
        contractAddendum.Order__c = order.Id;
        insert contractAddendum;

        List<Attachment> attachments = new List<Attachment>();
        Attachment newAttachment = new Attachment();
        newAttachment.ParentId = contractAddendum.Id;
        newAttachment.Body = Blob.valueOf('123');
        newAttachment.Name = '123';
        attachments.add(newAttachment);

        Attachment newAttachment2 = new Attachment();
        newAttachment2.ParentId = contractAddendum.Id;
        newAttachment2.Body = Blob.valueOf('123');
        newAttachment2.Name = '123';
        attachments.add(newAttachment2);

        insert attachments;

        Contract_Addendum__c contractAddendum2 = [SELECT Id, Attachment_Name__c FROM Contract_Addendum__c LIMIT 1];
        System.assertNotEquals(null, contractAddendum2.Attachment_Name__c);
    }

}