src/objects/Invoice_Line__c.object
<CustomObject>
    <description>The line items on Invoices, such as products etc.</description>
    <fields>
        <fullName>Job_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Rate Plan Charge</label>
        <referenceTo>Job_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price_Type__c</fullName>
        <description>The frequency at which the charge will be billed (One Time, Monthly, Quarterly, Annual etc)</description>
        <inlineHelpText>The frequency at which the charge will be billed (One Time, Monthly, Quarterly, Annual etc)</inlineHelpText>
        <label>Price Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Price_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Split_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Split Invoice</label>
        <type>Checkbox</type>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <label>Line Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Mid_Term_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mid Term Order</label>
        <type>Checkbox</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order (InvoiceIT) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Job_Rate_Plan_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Price_Type__c</fullName>
        <inlineHelpText>The frequency at which the charge will be billed (One Time, Monthly, Quarterly, Annual etc)</inlineHelpText>
        <label>Price Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One Time</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Half Yearly</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Usage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order Rate Plan Charge</label>
    <nameField>
        <label>Order Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Price_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>One Time</fullName>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Half Yearly</fullName>
    </customValue>
    <customValue>
        <fullName>Annual</fullName>
    </customValue>
    <customValue>
        <fullName>Usage</fullName>
    </customValue>
    <masterLabel>Price Type</masterLabel>
</GlobalValueSet>

src/classes/VTMig_IITClassAfterOnInvoiceLine.cls
/**
 * Created by triciaigoe on 2019-11-25.
 */

public with sharing class VTMig_IITClassAfterOnInvoiceLine {

    public void handleAfterOnInvoiceLine(map<Id,Invoice_Line__c > newMap, map<Id,Invoice_Line__c > oldMap) {
        if(trigger.isInsert) {
            list<Invoice_Line__c> invoiceLines;
            invoiceLines = [SELECT Id
            FROM Invoice_Line__c
            WHERE Id In : newMap.keySet()
            //AND
            //Job__r.Mid_Term_Order__c = true
            AND
            Split_Invoice__c = false
            AND
            Job_Rate_Plan_Charge__r.Price_Type__c != 'One Time'
            AND
            Job_Rate_Plan_Charge__r.Price_Type__c != 'Monthly'
            ];

            if(invoiceLines.size() > 0) {
                VTMig_IITCommonUtilClass.calculateQuantity(invoiceLines);
            }
        }
    }
}