src/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BMS_Contract_Year__c</fullName>
        <inlineHelpText>This is the year of the actual contract for billing purposes. We will need to use to initially calculate the Billing Amount</inlineHelpText>
        <label>BMS Contract Year</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Value__c</fullName>
        <inlineHelpText>Discount offered on this order</inlineHelpText>
        <label>Discount Value</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IITIntended_Use__c</fullName>
        <label>Intended Use</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Intended_Use</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Master_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipName>ChildOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mid_Term_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mid Term Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_total__c</fullName>
        <inlineHelpText>Quantity * Unit Price</inlineHelpText>
        <label>Subtotal</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Withholding_Tax_Percentage__c</fullName>
        <inlineHelpText>Select the Withholding Tax Percentage</inlineHelpText>
        <label>Withholding Tax Percentage</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order (InvoiceIT) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order_Commissions__c.object
<CustomObject>
    <description>This object is defined to identify the Agents that are to receive commission for a specific order based on the Product and the standard or adjusted commission rates.</description>
    <fields>
        <fullName>Commission_Basis__c</fullName>
        <inlineHelpText>Most Rental commissions based at the Master Order Level. Some Custom / Split  commissions based on the Child Order. If this commission is based specifically on the individual child order, please select Child Order, and Edit the Child Order.</inlineHelpText>
        <label>Commission Basis</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Master Order</fullName>
                    <default>true</default>
                    <label>Master Order</label>
                </value>
                <value>
                    <fullName>Child Order</fullName>
                </value>
                <value>
                    <fullName>Sale Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Order Commissions</relationshipLabel>
        <relationshipName>Order_Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_for_Commission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the Applicable Order to be commissioned</inlineHelpText>
        <label>Order for Commission</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Order Commissions</relationshipLabel>
        <relationshipName>Order_Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Agent__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Select a KV Partner Account as the Sales Agent.</inlineHelpText>
        <label>Sales Agent</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select an appropriate Partner Account.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>KV Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Commissions</relationshipLabel>
        <relationshipName>Order_Commissions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year1_Commission__c</fullName>
        <inlineHelpText>Select the First Year Commission Rate for this order</inlineHelpText>
        <label>Year1 Commission</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Order Commissions</label>
    <nameField>
        <displayFormat>OCOM-{0000}</displayFormat>
        <label>Commissionable Agents Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Partner_Commission_Rates__c.object
<CustomObject>
    <description>This custom object allow users to create records to define stand commission rates that are based on a Type of Commission and related to Products (InvoiceIT)</description>
    <fields>
        <fullName>Partner_Agent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the Partner / Sales Agent</inlineHelpText>
        <label>Partner / Agent Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>KV Partner</value>
            </filterItems>
            <infoMessage>This currently looks up to KV Partners. The value entered does not exist or does not match filter criteria. Remove filter criteria to search all accounts.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Commission Rates</relationshipLabel>
        <relationshipName>Partner_Commission_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This looks up to the InvoiceIT Product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Partner Commission Rates</relationshipLabel>
        <relationshipName>Partner_Commission_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard_Comm__c</fullName>
        <inlineHelpText>Enter the standard commission for this Partner Agent for the selected Product for all subsequent years after year 1</inlineHelpText>
        <label>Standard Comm (after Yr1)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Year1_Commission__c</fullName>
        <inlineHelpText>Commission for Year 1. This is specific to Rentals and Subscriptions</inlineHelpText>
        <label>Year1 Commission</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Partner Commission Rates</label>
    <nameField>
        <displayFormat>PCR-{0000}</displayFormat>
        <label>Partner Commission Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Commission Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <label>Invoice IT Product</label>
    <nameField>
        <label>InvoiceIT Product  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice IT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderCommissionTriggerTest.cls
/**
 * Created by triciaigoe on 2019-11-13.
 */
@isTest
public with sharing class OrderCommissionTriggerTest {

    @TestSetup
    public static void OrderCommisionTrigger() {

        //Partner Creation
        Account acc = New Account();
        acc.RecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('KV Partner').getRecordTypeId();
        acc.Name = 'TestAcc';
        insert acc;

        //Customer Creation
        Account acc2 = New Account();
        acc2.RecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('KV Customers').getRecordTypeId();
        acc2.Name = 'TestAcc2';
        insert acc2;

        //Master order Creation
        Job__c masterOrder = new Job__c(Account__c = acc2.id, Sub_Total__c = 100, Discount_Value__c = 0);
        masterOrder.Account__c = acc2.Id;
        masterOrder.IITIntended_Use__c = 'LOCAL UK WATERS';
        masterOrder.Withholding_Tax_Percentage__c = 10;
        masterOrder.BMS_Contract_Year__c = 1;
        masterOrder.RecordTypeId = Schema.SObjectType.Job__c.getRecordTypeInfosByName().get('Master Order').getRecordTypeId();
        insert masterOrder;


        //Child Order Creation
        Job__c childOrder = new Job__c(Account__c = acc2.id, Sub_Total__c = 100, Discount_Value__c = 0);
        childOrder.Account__c = acc2.Id;
        childOrder.IITIntended_Use__c = 'LOCAL UK WATERS';
        childOrder.Withholding_Tax_Percentage__c = 10;
        childOrder.BMS_Contract_Year__c = 1;
        childOrder.Mid_Term_Order__c = true;
        childOrder.Master_Order__c = masterOrder.id;
        childOrder.RecordTypeId = Schema.SObjectType.Job__c.getRecordTypeInfosByName().get('Child Order').getRecordTypeId();
        insert childOrder;


        //Product Creation
        Product__c invoiceProduct = New Product__c(Name = '123');
        insert invoiceProduct;

        //Partner Commission Record Creation
        Partner_Commission_Rates__c pcr = New Partner_Commission_Rates__c();
        pcr.Partner_Agent_Account__c = acc.Id;
        pcr.Product__c = invoiceProduct.id;
        pcr.Standard_Comm__c = 1.0;
        pcr.Year1_Commission__c = 1.0;
        insert pcr;

    }

    @IsTest
    public static void testInsert() {

        Product__c invoiceProduct = [SELECT Id FROM Product__c];
        Account acc = [SELECT Id FROM Account WHERE RecordType.Name = 'KV Partner'];
        Job__c childOrder = [SELECT Id FROM Job__c WHERE RecordType.Name = 'Child Order'];
        Job__c masterOrder = [SELECT Id FROM Job__c WHERE RecordType.Name = 'Master Order'];


        //OrderCommision Creation
        list<Order_Commissions__c> orderCommissions = New list<Order_Commissions__c>();
        Order_Commissions__c oc = New Order_Commissions__c();
        oc.Order_Product__c = invoiceProduct.id;
        oc.Sales_Agent__c = acc.id;
        oc.Order_for_Commission__c = childOrder.id;
        orderCommissions.add(oc);

        Order_Commissions__c oc1 = New Order_Commissions__c();
        oc1.Order_Product__c = invoiceProduct.id;
        oc1.Sales_Agent__c = acc.id;
        oc1.Order_for_Commission__c = masterOrder.id;
        oc1.Commission_Basis__c = 'Master Order';
        orderCommissions.add(oc1);

        Order_Commissions__c oc2 = New Order_Commissions__c();
        oc2.Order_Product__c = invoiceProduct.id;
        oc2.Sales_Agent__c = acc.id;
        oc2.Order_for_Commission__c = masterOrder.id;
        orderCommissions.add(oc2);

        insert orderCommissions;

    }

    @IsTest
    public static void testUpdate(){
        Job__c childOrder = [SELECT Id FROM Job__c WHERE RecordType.Name = 'Child Order'];
        Product__c invoiceProduct = [SELECT Id FROM Product__c];
        Account acc = [SELECT Id FROM Account WHERE RecordType.Name = 'KV Partner'];
        Order_Commissions__c oc = New Order_Commissions__c();
        oc.Order_Product__c = invoiceProduct.id;
        oc.Sales_Agent__c = acc.id;
        oc.Order_for_Commission__c = childOrder.id;
        insert oc;

        update oc;
    }

}