src/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Alignment_Date_1__c</fullName>
        <label>Alignment Date 1</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Alignment_Date_2__c</fullName>
        <label>Alignment Date 2</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Despatch_Date__c</fullName>
        <label>Despatch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initial_Term__c</fullName>
        <label>Initial Term</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Activation_Date__c</fullName>
        <label>Service Start Date / Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_End_Date__c</fullName>
        <label>Service End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Awaiting Customer Signature</fullName>
                </value>
                <value>
                    <fullName>Ready for Admin Processing</fullName>
                </value>
                <value>
                    <fullName>Administration in Progress</fullName>
                </value>
                <value>
                    <fullName>Order Entry Complete</fullName>
                </value>
                <value>
                    <fullName>Ready for Fulfillment</fullName>
                </value>
                <value>
                    <fullName>In Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Ready for Dispatch</fullName>
                </value>
                <value>
                    <fullName>In Service</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Registration</fullName>
                </value>
                <value>
                    <fullName>Enrollment</fullName>
                </value>
                <value>
                    <fullName>Awaiting Documents</fullName>
                </value>
                <value>
                    <fullName>Documents Recieved</fullName>
                </value>
                <value>
                    <fullName>Documents sent for Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment Passed</fullName>
                </value>
                <value>
                    <fullName>Certificate Dispatched</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Awaiting Return</fullName>
                </value>
                <value>
                    <fullName>On boarding in progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order (InvoiceIT) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Job_Product__c.object
<CustomObject>
    <fields>
        <fullName>Job__c</fullName>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Job_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <externalId>true</externalId>
        <label>Product Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Product</label>
    <nameField>
        <label>Order Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Rate_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Job_Product__c</fullName>
        <label>Order Product</label>
        <referenceTo>Job_Product__c</referenceTo>
        <relationshipLabel>Order Rate Plans</relationshipLabel>
        <relationshipName>Order_Rate_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Rate Plan</label>
    <nameField>
        <label>Order Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Rate_Plan_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Job_Rate_Plan__c</fullName>
        <inlineHelpText>Shows the Rate Plan that has been selected or automatically applied for this charge.</inlineHelpText>
        <label>Order Rate Plan</label>
        <referenceTo>Job_Rate_Plan__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Job_Rate_Plan_Charge</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Charge_Category__c</fullName>
        <inlineHelpText>Use this field if you would want to configure different VAT percentages for different categories.</inlineHelpText>
        <label>Tax Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Taxable</fullName>
                    <default>true</default>
                    <label>Taxable</label>
                </value>
                <value>
                    <fullName>Non Taxable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Shows the name of the order charge.</inlineHelpText>
        <label>Product Rate Plan Charge</label>
        <referenceTo>Product_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Job_Rate_Plan_Charge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Activation_Date__c</fullName>
        <label>Service Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_End_Date__c</fullName>
        <label>Service End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Shows the status of the order charge. The status field can be used to control whether the order line should be invoiced or provisioned for example.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready to Bill</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Awaiting Customer Signature</fullName>
                </value>
                <value>
                    <fullName>Ready for Admin Processing</fullName>
                </value>
                <value>
                    <fullName>Administration in Progress</fullName>
                </value>
                <value>
                    <fullName>Awaiting Return</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscription Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Title Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Of_Measurement__c</fullName>
        <inlineHelpText>The Unit of Measure (UOM).</inlineHelpText>
        <label>UOM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>UOM</valueSetName>
        </valueSet>
    </fields>
    <label>Order Rate Plan Charge</label>
    <nameField>
        <label>Order Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Product_Code__c</fullName>
        <externalId>true</externalId>
        <label>Product Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(TODAY() &gt;= Valid_From_Date__c &amp;&amp; (TODAY() &lt;= Valid_To_Date__c || ISBLANK(Valid_To_Date__c)), &quot;Active&quot;, IF(Valid_From_Date__c &gt; TODAY(), &quot;Future&quot; , &quot;Expired&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Invoice IT Product</label>
    <nameField>
        <label>InvoiceIT Product  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice IT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Rate_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product Rate Plans</relationshipLabel>
        <relationshipName>Product_Rate_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(TODAY() &gt;= Valid_From_Date__c &amp;&amp; (TODAY() &lt;= Valid_To_Date__c || ISBLANK(Valid_To_Date__c)), &quot;Active&quot;, IF(Valid_From_Date__c &gt; TODAY(), &quot;Future&quot; , &quot;Expired&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Product Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Rate_Plan_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Product_Charge_Category__c</fullName>
        <description>Use this field if you would want to configure different Tax or VAT percentages for different categories.</description>
        <inlineHelpText>Use this field if you would want to configure different Tax or VAT percentages for different categories.</inlineHelpText>
        <label>Tax Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Taxable</fullName>
                    <default>true</default>
                    <label>Taxable</label>
                </value>
                <value>
                    <fullName>Non Taxable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscription Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Title Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Of_Measurement__c</fullName>
        <description>Unit of measurement
(Unit, kilo, tonne etc)</description>
        <inlineHelpText>Unit of measurement
(Unit, kilo, tonne etc)</inlineHelpText>
        <label>UOM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>UOM</valueSetName>
        </valueSet>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Product Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VTMig_UpdateOrderStatus.cls
/**
 * Created by triciaigoe on 2019-11-20.
 */

public with sharing class VTMig_UpdateOrderStatus {

    public Id orderId {get; set;}
    public Job__c order {get; set;}
    public List<Job_Rate_Plan_Charge__c> selectedCharges {get;set;}

    public VTMig_UpdateOrderStatus(ApexPages.StandardController ctrlr){
        orderId = ApexPages.currentPage().getParameters().get('Id');
        selectedCharges = new List<Job_Rate_Plan_Charge__c>();
        order = [
                SELECT Id, Account__c, Name, Status__c, Despatch_Date__c, Service_Activation_Date__c, Service_End_Date__c, Alignment_Date_1__c,
                        Alignment_Date_2__c, Initial_Term__c, Order_Number__c, Account__r.RecordType.DeveloperName
                FROM Job__c WHERE Id = : orderId
        ];
        selectedCharges = [SELECT Id, Name, Product_Charge_Category__c, Subscription_Product__c, Job_Rate_Plan__r.Job_Product__r.Name,
                Job_Rate_Plan__r.Job_Product__r.Product__c, Product_Rate_Plan_Charge__c, Job_Rate_Plan__r.Job_Product__r.Product_Code__c,
                Title_Product__c, Unit_Of_Measurement__c, Price_Type__c, Price_Format__c, Unit_Price__c, Uplift__c, Auto_Renew__c, Courier__c,
                Quantity__c, Job_Rate_Plan__r.Product_Rate_Plan__c, Row_Total__c, Airway_Bill_Number__c, Service_End_Date__c,
                Service_Activation_Date__c, Status__c, Discount_Value__c
        FROM Job_Rate_Plan_Charge__c WHERE Order__c = : orderId];
    }

    public PageReference saveOrder(){
        if((order.Status__c == 'Order Entry Complete')
                && order.Account__r.RecordType.DeveloperName == 'KV_Prospect') {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Please change account to KV Customer'));
        } else {
            Job__c newOrder = new Job__c();
            newOrder.Despatch_Date__c = order.Despatch_Date__c;
            newOrder.Service_Activation_Date__c = order.Service_Activation_Date__c;
            newOrder.Id = orderId;
            newOrder.Status__c = order.Status__c;
            newOrder.Alignment_Date_2__c = order.Alignment_Date_2__c;
            newOrder.Alignment_Date_1__c = order.Alignment_Date_1__c;
            newOrder.Initial_Term__c = order.Initial_Term__c;
            try{
                update newOrder;
                for(Job_Rate_Plan_Charge__c selectedCharge : selectedCharges) {
                    selectedCharge.Price__c = selectedCharge.Unit_Price__c * selectedCharge.Quantity__c;
                    if(selectedCharge.Discount_Value__c == null) {
                        selectedCharge.Discount_Value__c = 0;
                    }
                    selectedCharge.Net_Total__c = selectedCharge.Price__c - selectedCharge.Discount_Value__c;
                }
                update selectedCharges;
                PageReference pageRef = new PageReference('/' + orderId);
                return pageRef;
            } catch(Exception ex) {
                if(ex.getMessage().contains('Shipping Account')) {
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Please add Shipping Account'));
                } else {
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,ex.getMessage()));
                }

            }
        }


        return null;
    }

}