src/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IITIntended_Use__c</fullName>
        <label>Intended Use</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Intended_Use</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal_Entity__c</fullName>
        <label>Legal Entity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Legal_Entity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Platform_or_Vessel_detail__c</fullName>
        <inlineHelpText>Select the specific platform or vessel category that is related to specific Titles.</inlineHelpText>
        <label>Vessel or Platform Detail</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Vessel_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipping_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipping Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary(Shipping) Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Shipping Contact)</relationshipLabel>
        <relationshipName>Job1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wet_or_Dry_Cargo__c</fullName>
        <inlineHelpText>If using a Full VOD, select Wet or Dry Cargo</inlineHelpText>
        <label>Wet or Dry Cargo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dry Cargo</fullName>
                </value>
                <value>
                    <fullName>Wet Cargo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order (InvoiceIT) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Job_Product__c.object
<CustomObject>
    <fields>
        <fullName>Job__c</fullName>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Job_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Product</label>
    <nameField>
        <label>Order Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Rate_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Job_Product__c</fullName>
        <label>Order Product</label>
        <referenceTo>Job_Product__c</referenceTo>
        <relationshipLabel>Order Rate Plans</relationshipLabel>
        <relationshipName>Order_Rate_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Rate Plan</label>
        <referenceTo>Product_Rate_Plan__c</referenceTo>
        <relationshipLabel>Order Rate Plans</relationshipLabel>
        <relationshipName>Order_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Rate Plan</label>
    <nameField>
        <label>Order Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Rate_Plan_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Job_Rate_Plan__c</fullName>
        <inlineHelpText>Shows the Rate Plan that has been selected or automatically applied for this charge.</inlineHelpText>
        <label>Order Rate Plan</label>
        <referenceTo>Job_Rate_Plan__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Job_Rate_Plan_Charge</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price_Format__c</fullName>
        <label>Pricing Model</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pricing_Model</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price_Type__c</fullName>
        <inlineHelpText>The frequency at which the charge will be billed (One Time, Monthly, Quarterly, Annual etc)</inlineHelpText>
        <label>Price Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One Time</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Half Yearly</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Usage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <inlineHelpText>Shows the Sub Total for the order charge which is calculated by multiplying the unit price by the quantity being ordered. (Quantity * Unit Price)</inlineHelpText>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Charge_Category__c</fullName>
        <inlineHelpText>Use this field if you would want to configure different VAT percentages for different categories.</inlineHelpText>
        <label>Tax Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Taxable</fullName>
                    <default>true</default>
                    <label>Taxable</label>
                </value>
                <value>
                    <fullName>Non Taxable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Shows the name of the order charge.</inlineHelpText>
        <label>Product Rate Plan Charge</label>
        <referenceTo>Product_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Job_Rate_Plan_Charge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>The quantity of products/services being sold</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscription Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Title Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Of_Measurement__c</fullName>
        <inlineHelpText>The Unit of Measure (UOM).</inlineHelpText>
        <label>UOM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>UOM</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <inlineHelpText>The unit selling price of the order line</inlineHelpText>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Order Rate Plan Charge</label>
    <nameField>
        <label>Order Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Rate_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product Rate Plans</relationshipLabel>
        <relationshipName>Product_Rate_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Product Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Rate_Plan_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Price_Type__c</fullName>
        <description>This will specify whether price is onetime, weekly, monthly etc or usage(metered) based.</description>
        <label>Price Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One Time</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Half Yearly</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Usage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Charge_Category__c</fullName>
        <description>Use this field if you would want to configure different Tax or VAT percentages for different categories.</description>
        <inlineHelpText>Use this field if you would want to configure different Tax or VAT percentages for different categories.</inlineHelpText>
        <label>Tax Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Taxable</fullName>
                    <default>true</default>
                    <label>Taxable</label>
                </value>
                <value>
                    <fullName>Non Taxable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <label>Product Rate Plan</label>
        <referenceTo>Product_Rate_Plan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charges</relationshipLabel>
        <relationshipName>Product_Rate_Plan_Charges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscription Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Title Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Of_Measurement__c</fullName>
        <description>Unit of measurement
(Unit, kilo, tonne etc)</description>
        <inlineHelpText>Unit of measurement
(Unit, kilo, tonne etc)</inlineHelpText>
        <label>UOM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>UOM</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <description>Unit Selling Price</description>
        <inlineHelpText>Unit Selling Price</inlineHelpText>
        <label>Unit Selling Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Product Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Legal_Entity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>VMA</fullName>
    </customValue>
    <customValue>
        <fullName>VMI</fullName>
    </customValue>
    <customValue>
        <fullName>VCR</fullName>
        <isActive>false</isActive>
        <label>VCR</label>
    </customValue>
    <customValue>
        <fullName>VTS</fullName>
        <isActive>false</isActive>
        <label>VTS</label>
    </customValue>
    <masterLabel>Legal Entity</masterLabel>
</GlobalValueSet>

src/globalValueSets/Vessel_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bulk Carrier</fullName>
    </customValue>
    <customValue>
        <fullName>Chemical Tanker</fullName>
    </customValue>
    <customValue>
        <fullName>Container</fullName>
    </customValue>
    <customValue>
        <fullName>Container Ship</fullName>
    </customValue>
    <customValue>
        <fullName>Crude Oil Tanker</fullName>
    </customValue>
    <customValue>
        <fullName>Crude Tanker</fullName>
    </customValue>
    <customValue>
        <fullName>Dry Cargo</fullName>
    </customValue>
    <customValue>
        <fullName>Gas Carrier</fullName>
    </customValue>
    <customValue>
        <fullName>General Cargo Vessel</fullName>
    </customValue>
    <customValue>
        <fullName>Heavy Lift Vessel</fullName>
    </customValue>
    <customValue>
        <fullName>LNG Carriers</fullName>
    </customValue>
    <customValue>
        <fullName>Misc</fullName>
    </customValue>
    <customValue>
        <fullName>Offshore</fullName>
    </customValue>
    <customValue>
        <fullName>Offshore Supply Vessel</fullName>
    </customValue>
    <customValue>
        <fullName>Passenger</fullName>
    </customValue>
    <customValue>
        <fullName>Product Oil Tanker</fullName>
    </customValue>
    <customValue>
        <fullName>Reefer</fullName>
    </customValue>
    <customValue>
        <fullName>RO-RO PCC</fullName>
    </customValue>
    <customValue>
        <fullName>Seismic Survey Vessels</fullName>
    </customValue>
    <customValue>
        <fullName>Tankers</fullName>
    </customValue>
    <customValue>
        <fullName>Tugs</fullName>
    </customValue>
    <masterLabel>Vessel Types</masterLabel>
</GlobalValueSet>

src/classes/VTMig_AddOrderProduct.cls
/**
 * Created by triciaigoe on 2019-11-11.
 */

public with sharing class VTMig_AddOrderProduct {

        public Id orderId {get; set;}
        public Job__c order {get; set;}
        public String prodSearchText {get; set;}
        public List<Product__c> productList {get; set;}
        public String selectedProductId {get; set;}
        public String selectedPlanId {get; set;}
        public String selectedChargeId {get; set;}
        public String removeChargeId {get; set;}
        public Decimal overallDiscount {get;set;}
        public Decimal grandTotal {get;set;}
        public Product_Rate_Plan_Charge__c selectedCharge {get; set;}
        public List<Product_Rate_Plan__c> plans {get; set;}
        public List<ProdCharge> prodCharges {get; set;}
        public Boolean showProducts {get; set;}
        public Boolean showPlans {get; set;}
        public Boolean showCharges {get; set;}
        public Boolean showChosenCharges {get; set;}
        public String pageStep {get; set;}
        public List<OrderCharge> selectedCharges {get;set;}
        public List<ProdCharge> selectedProdCharges {get;set;}

        public VTMig_AddOrderProduct(ApexPages.StandardController ctrlr){
            orderId = ApexPages.currentPage().getParameters().get('Id');
            selectedCharges = new List<OrderCharge>();
            prodCharges = new List<ProdCharge>();
            productList = new List<Product__c>();
            selectedProdCharges = new List<ProdCharge>();
            showProducts = false;
            showPlans = false;
            showCharges = false;
            pageStep = '1';
            grandTotal = 0;
            order = [
                    SELECT Id, Account__c, Shipping_Contact__c, Shipping_Account__c, Legal_Entity__c, Partner_Agent__c, IITIntended_Use__c,
                            Wet_or_Dry_Cargo__c, Platform_or_Vessel_detail__c, Name
                    FROM Job__c WHERE Id = : orderId
            ];
            List<Job_Rate_Plan_Charge__c> currentCharges = [SELECT Id, Name, Product_Charge_Category__c, Subscription_Product__c, Job_Rate_Plan__r.Job_Product__r.Name,
                    Job_Rate_Plan__r.Job_Product__r.Product__c, Product_Rate_Plan_Charge__c,
                    Title_Product__c, Unit_Of_Measurement__c, Price_Type__c, Price_Format__c, Unit_Price__c,
                    Quantity__c, Job_Rate_Plan__r.Job_Product__r.Product_Code__c, Job_Rate_Plan__r.Product_Rate_Plan__c
            FROM Job_Rate_Plan_Charge__c WHERE Order__c = : orderId];
            if(currentCharges.size() > 0) {
                for(Job_Rate_Plan_Charge__c currentCharge : currentCharges) {
                    ProdCharge singleProdCharge = new ProdCharge();
                    singleProdCharge.prodCharge = [SELECT Id, Name, Product_Charge_Category__c, Subscription_Product__c, Product_Rate_Plan__r.Product__r.Name,
                            Title_Product__c, Unit_Of_Measurement__c, Price_Type__c, Pricing_Format__c, Unit_Price__c, Product_Rate_Plan__r.Product__r.Product_Code__c
                    FROM Product_Rate_Plan_Charge__c WHERE Id = : currentCharge.Product_Rate_Plan_Charge__c];
                    singleProdCharge.quantity = Integer.valueOf(currentCharge.Quantity__c);
                    singleProdCharge.planId = currentCharge.Job_Rate_Plan__r.Product_Rate_Plan__c;
                    singleProdCharge.prodId = currentCharge.Job_Rate_Plan__r.Job_Product__r.Product__c;
                    selectedProdCharges.add(singleProdCharge);
                }
                showChosenCharges = true;
            } else {
                showChosenCharges = false;
            }
        }

        public void openList(){
            String activeStatus = 'Active';
            String query = 'SELECT Id, Name, Description__c, Effective_Period__c, External_ID__c, ' +
                    'GL_Account_Receivable_Number__c, Manufacturer__c, Product_Code__c, Product_Family__c, ' +
                    'Status__c, Unique_Identifier__c, Valid_From_Date__c, Valid_To_Date__c ' +
                    'FROM Product__c WHERE Status__c = : activeStatus ';
            if(String.isNotEmpty(prodSearchText)){
                String prodSearch = '%' + prodSearchText + '%';
                query = query + 'AND Name LIKE : prodSearch';
            }
            productList = Database.query(query);
            showProducts = true;
            showPlans = false;
            showCharges = false;
        }

        public void selectProduct(){
            System.debug(selectedProductId);
            showProducts = false;
            showCharges = false;
            plans = [SELECT Id, Name, Description__c FROM Product_Rate_Plan__c WHERE Status__c = 'Active' AND Product__c = : selectedProductId];
            showPlans = true;
        }

        public void selectPlan(){
            showProducts = false;
            showPlans = false;
            List<Product_Rate_Plan_Charge__c> charges = [SELECT Id, Name, Product_Charge_Category__c, Subscription_Product__c, Product_Rate_Plan__r.Product__r.Name,
                    Title_Product__c, Unit_Of_Measurement__c, Price_Type__c, Pricing_Format__c, Unit_Price__c, Quantity__c, Product_Rate_Plan__r.Product__r.Product_Code__c
            FROM Product_Rate_Plan_Charge__c WHERE Product_Rate_Plan__c = : selectedPlanId];
            for(Product_Rate_Plan_Charge__c charge : charges) {
                ProdCharge newProdCharge = new ProdCharge();
                newProdCharge.prodCharge = charge;
                newProdCharge.prodId = selectedProductId;
                newProdCharge.planId = selectedPlanId;
                prodCharges.add(newProdCharge);
            }
            showCharges = true;
        }

        public void selectCharge(){

            Integer quantity = 0;
            ProdCharge selectedProdCharge = new ProdCharge();
            for(ProdCharge prodCharge : prodCharges) {
                if(prodCharge.prodCharge.Id == selectedChargeId) {
                    quantity = prodCharge.quantity;
                    selectedProdCharge = prodCharge;
                }
            }
            selectedProdCharges.add(selectedProdCharge);
            prodSearchText = '';
            selectedChargeId = '';
            selectedPlanId = '';
            selectedProductId = '';
            plans.clear();
            prodCharges.clear();
            showCharges = false;
            showPlans = false;
            showProducts = false;
            showChosenCharges = true;
        }

        public void removeCharge(){

            for(Integer i = 0; i<selectedProdCharges.size(); i++) {
                if(removeChargeId == selectedProdCharges[i].prodCharge.Id) {
                    selectedProdCharges.remove(i);
                }
            }
            removeChargeId = '';
        }

        public void step2(){

            for(ProdCharge selectedProdCharge : selectedProdCharges) {
                OrderCharge currentCharge = new OrderCharge();
                currentCharge.prodCharge = selectedProdCharge;
                currentCharge.orderProduct = configOrderProd(selectedProdCharge.prodId);
                currentCharge.orderRatePlan = configOrderPlan(selectedProdCharge.planId, currentCharge.orderProduct.Id);
                currentCharge.orderRatePlanCharge = configOrderCharge(selectedProdCharge.prodCharge.Id, currentCharge.orderRatePlan.Id, selectedProdCharge.quantity);
                selectedCharges.add(currentCharge);
                grandTotal = grandTotal + currentCharge.orderRatePlanCharge.Price__c;
            }
            pageStep = '2';
        }

        public void step1(){
            selectedCharges.clear();
            pageStep = '1';
        }

        public PageReference saveProducts(){

            List<Job_Product__c> OrderProducts = new List<Job_Product__c>();
            List<Job_Rate_Plan__c> OrderRatePlans = new List<Job_Rate_Plan__c>();
            List<Job_Rate_Plan_Charge__c> OrderCharges = new List<Job_Rate_Plan_Charge__c>();
            for(OrderCharge OrderCharge : selectedCharges) {
                OrderProducts.add(OrderCharge.orderProduct);
            }
            insert OrderProducts;
            for(OrderCharge OrderCharge : selectedCharges) {
                Id OrderProdId;
                for(Job_Product__c OrderProduct : OrderProducts) {
                    if(OrderProduct.Product__c == OrderCharge.prodCharge.prodId){
                        OrderProdId = OrderProduct.Id;
                    }
                }
                Job_Rate_Plan__c OrderRatePlan = configOrderPlan(OrderCharge.prodCharge.planId, OrderProdId);
                OrderRatePlans.add(OrderRatePlan);
            }
            insert OrderRatePlans;
            Decimal runningTotal = 0;
            for(OrderCharge OrderCharge : selectedCharges) {
                Id ratePlanId;
                for(Job_Rate_Plan__c OrderRatePlan : OrderRatePlans) {
                    if(OrderRatePlan.Product_Rate_Plan__c == OrderCharge.prodCharge.planId) {
                        ratePlanId = OrderRatePlan.Id;
                    }
                }
                runningTotal = runningTotal + OrderCharge.orderRatePlanCharge.Unit_Price__c * OrderCharge.orderRatePlanCharge.Quantity__c;
                Job_Rate_Plan_Charge__c OrderRatePlanCharge = configOrderCharge(OrderCharge.prodCharge.prodCharge.Id, ratePlanId, OrderCharge.prodCharge.quantity);
                OrderCharges.add(OrderRatePlanCharge);
            }
            insert OrderCharges;
            order.Discount_Value__c = runningTotal - grandTotal;
            order.Total__c = grandTotal;
            update order;
            PageReference pageRef = new PageReference('/'+orderId);
            return pageRef;
        }

        public Job_Rate_Plan__c configOrderPlan(String planId, String OrderProdId) {

            Product_Rate_Plan__c ratePlan = [SELECT Id, Name, Description__c, Sequence_Number__c FROM Product_Rate_Plan__c WHERE Id =: planId];
            Job_Rate_Plan__c OrderRatePlan = new Job_Rate_Plan__c();
            OrderRatePlan.Name = ratePlan.Name;
            OrderRatePlan.Product_Rate_Plan__c = ratePlan.Id;
            OrderRatePlan.Description__c = ratePlan.Description__c;
            OrderRatePlan.Sequence_Number__c = ratePlan.Sequence_Number__c;
            OrderRatePlan.Job_Product__c = OrderProdId;
            return OrderRatePlan;
        }

        public Job_Product__c configOrderProd(String prodId) {

            Product__c chosenProduct = [SELECT Id, Description__c, Product_Code__c, Product_Family__c, Name FROM Product__c WHERE Id =: prodId];
            Job_Product__c OrderProduct = new Job_Product__c();
            OrderProduct.Name = chosenProduct.Name;
            OrderProduct.Description__c = chosenProduct.Description__c;
            OrderProduct.Product__c = prodId;
            OrderProduct.Product_Family__c = chosenProduct.Product_Family__c;
            OrderProduct.Product_Code__c = chosenProduct.Product_Code__c;
            OrderProduct.Job__c = orderId;
            return OrderProduct;
        }

        public Job_Rate_Plan_Charge__c configOrderCharge(String chargeId, String planId, Integer quantityInteger) {
            Product_Rate_Plan_Charge__c charge = [SELECT Id, Name, Product_Charge_Category__c, Subscription_Product__c,
                    Title_Product__c, Unit_Of_Measurement__c, Price_Type__c, Pricing_Format__c, Unit_Price__c
            FROM Product_Rate_Plan_Charge__c WHERE Id =: chargeId];
            Job_Rate_Plan_Charge__c newCharge = new Job_Rate_Plan_Charge__c();
            newCharge.Name = charge.Name;
            newCharge.Product_Charge_Category__c = charge.Product_Charge_Category__c;
            newCharge.Subscription_Product__c = charge.Subscription_Product__c;
            newCharge.Title_Product__c = charge.Title_Product__c;
            newCharge.Unit_Of_Measurement__c = charge.Unit_Of_Measurement__c;
            newCharge.Price_Type__c = charge.Price_Type__c;
            newCharge.Price_Format__c = charge.Pricing_Format__c;
            newCharge.Unit_Price__c = charge.Unit_Price__c;
            newCharge.External_Id__c = selectedPlanId;
            newCharge.Product_Rate_Plan_Charge__c = charge.Id;
            newCharge.Quantity__c = quantityInteger;
            newCharge.Job_Rate_Plan__c = planId;
            newCharge.Price__c = charge.Unit_Price__c * quantityInteger;
            newCharge.Discount_Percent__c = 0.00;
            newCharge.Order__c = orderId;
            return newCharge;
        }

        public void recalculate(){

            grandTotal = 0;
            for(OrderCharge selectedCharge: selectedCharges) {
                selectedCharge.orderRatePlanCharge.Price__c = selectedCharge.orderRatePlanCharge.Unit_Price__c * selectedCharge.orderRatePlanCharge.Quantity__c * (1-(selectedCharge.orderRatePlanCharge.Discount_Percent__c/100));
                selectedCharge.orderRatePlanCharge.Discount_Value__c = selectedCharge.orderRatePlanCharge.Unit_Price__c * selectedCharge.orderRatePlanCharge.Quantity__c - selectedCharge.orderRatePlanCharge.Price__c;
                grandTotal = grandTotal + selectedCharge.orderRatePlanCharge.Price__c;
            }
            if(overallDiscount > 0) {
                grandTotal = grandTotal * (1-(overallDiscount/100));
            }

        }

        public class OrderCharge{
            public ProdCharge prodCharge {get;set;}
            public Job_Rate_Plan__c orderRatePlan {get;set;}
            public Job_Product__c orderProduct {get;set;}
            public Job_Rate_Plan_Charge__c orderRatePlanCharge {get;set;}

            public OrderCharge(){}
        }

        public class ProdCharge{
            public Product_Rate_Plan_Charge__c prodCharge {get;set;}
            public Integer quantity {get;set;}
            public String prodId {get;set;}
            public String planId {get;set;}

            public ProdCharge(){}
        }

}