src/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount_Percent__c</fullName>
        <label>Discount Percent</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Discount_Value__c</fullName>
        <inlineHelpText>Discount offered on this order</inlineHelpText>
        <label>Discount Value</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order (InvoiceIT) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Job_Product__c.object
<CustomObject>
    <fields>
        <fullName>Job__c</fullName>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Job_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Product</label>
    <nameField>
        <label>Order Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Rate_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Job_Product__c</fullName>
        <label>Order Product</label>
        <referenceTo>Job_Product__c</referenceTo>
        <relationshipLabel>Order Rate Plans</relationshipLabel>
        <relationshipName>Order_Rate_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Rate Plan</label>
        <referenceTo>Product_Rate_Plan__c</referenceTo>
        <relationshipLabel>Order Rate Plans</relationshipLabel>
        <relationshipName>Order_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Rate Plan</label>
    <nameField>
        <label>Order Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Rate_Plan_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Discount_Percent__c</fullName>
        <inlineHelpText>The percentage discount that has been applied to the order charge.</inlineHelpText>
        <label>Discount %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Discount_Value__c</fullName>
        <inlineHelpText>The discount value that has been applied to the order charge.</inlineHelpText>
        <label>Discount Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Job_Rate_Plan__c</fullName>
        <inlineHelpText>Shows the Rate Plan that has been selected or automatically applied for this charge.</inlineHelpText>
        <label>Order Rate Plan</label>
        <referenceTo>Job_Rate_Plan__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Job_Rate_Plan_Charge</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Shows the order record that the charge is related to - click to be taken directly to the order</inlineHelpText>
        <label>Order</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Order_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <inlineHelpText>Shows the Sub Total for the order charge which is calculated by multiplying the unit price by the quantity being ordered. (Quantity * Unit Price)</inlineHelpText>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Shows the name of the order charge.</inlineHelpText>
        <label>Product Rate Plan Charge</label>
        <referenceTo>Product_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Order Rate Plan Charges</relationshipLabel>
        <relationshipName>Job_Rate_Plan_Charge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>The quantity of products/services being sold</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <inlineHelpText>The unit selling price of the order line</inlineHelpText>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Order Rate Plan Charge</label>
    <nameField>
        <label>Order Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Valid_From_Date__c</fullName>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <label>Invoice IT Product</label>
    <nameField>
        <label>InvoiceIT Product  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice IT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Rate_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product Rate Plans</relationshipLabel>
        <relationshipName>Product_Rate_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Valid_From_Date__c</fullName>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Product Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Rate_Plan_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <label>Product Rate Plan</label>
        <referenceTo>Product_Rate_Plan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charges</relationshipLabel>
        <relationshipName>Product_Rate_Plan_Charges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <description>Unit Selling Price</description>
        <inlineHelpText>Unit Selling Price</inlineHelpText>
        <label>Unit Selling Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Product Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VTMig_AddOrderProduct_Test.cls
/**
 * Created by triciaigoe on 2019-11-19.
 */
@IsTest
public with sharing class VTMig_AddOrderProduct_Test {

    @TestSetup
    static void setUpData(){

        Account newAccount = new Account();
        newAccount.Name = 'New Account';
        insert newAccount;

        Job__c newOrder = new Job__c();
        newOrder.Account__c = newAccount.Id;
        newOrder.Name = 'New Order';
        insert newOrder;

        Product__c newProduct = new Product__c();
        newProduct.Name = 'New Product';
        newProduct.Valid_From_Date__c = System.today();
        insert newProduct;

        Product_Rate_Plan__c newProductRatePlan = new Product_Rate_Plan__c();
        newProductRatePlan.Name = 'New Product Rate Plan';
        newProductRatePlan.Valid_From_Date__c = System.today();
        newProductRatePlan.Product__c = newProduct.Id;
        insert newProductRatePlan;

        Product_Rate_Plan_Charge__c newProductRatePlanCharge = new Product_Rate_Plan_Charge__c();
        newProductRatePlanCharge.Name = 'New Product Rate Plan Charge';
        newProductRatePlanCharge.Product_Rate_Plan__c = newProductRatePlan.Id;
        newProductRatePlanCharge.Unit_Price__c = 100;
        insert newProductRatePlanCharge;

        Job_Product__c orderProduct = new Job_Product__c();
        orderProduct.Job__c = newOrder.Id;
        orderProduct.Product__c = newProduct.Id;
        insert orderProduct;

        Job_Rate_Plan__c orderRatePlan = new Job_Rate_Plan__c();
        orderRatePlan.Product_Rate_Plan__c = newProductRatePlan.Id;
        orderRatePlan.Job_Product__c = orderProduct.Id;
        insert orderRatePlan;

    }

    @IsTest
    static void testOpenList(){

        Job__c theOrder = [SELECT Id FROM Job__c];

        Test.startTest();

        PageReference pageRef = Page.VTMig_AddOrderProducts;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id',theOrder.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(theOrder);
        VTMig_AddOrderProduct controller = new VTMig_AddOrderProduct(sc);

        controller.openList();
        controller.step1();
        System.assertEquals(controller.showProducts, true);

        Test.stopTest();
    }

    @IsTest
    static void testSelectPlanAndCharge(){

        Job__c newOrder = [SELECT Id FROM Job__c];

        Job_Rate_Plan__c orderRatePlan = [SELECT Id FROM Job_Rate_Plan__c];

        Product_Rate_Plan_Charge__c productRatePlanCharge = [SELECT Id FROM Product_Rate_Plan_Charge__c];

        Job_Rate_Plan_Charge__c orderRatePlanCharge = new Job_Rate_Plan_Charge__c();
        orderRatePlanCharge.Job_Rate_Plan__c = orderRatePlan.Id;
        orderRatePlanCharge.Quantity__c = 1;
        orderRatePlanCharge.Order__c = newOrder.Id;
        orderRatePlanCharge.Product_Rate_Plan_Charge__c = productRatePlanCharge.Id;
        orderRatePlanCharge.Unit_Price__c = 100;
        orderRatePlanCharge.Name = 'New Opp Rate Plan Charge';
        orderRatePlanCharge.Price__c = 100;
        orderRatePlanCharge.Discount_Value__c = 0;
        orderRatePlanCharge.Discount_Percent__c = 0;
        insert orderRatePlanCharge;

        Test.startTest();

        PageReference pageRef = Page.VTMig_ProductSelection;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id',newOrder.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(newOrder);
        VTMig_AddOrderProduct controller = new VTMig_AddOrderProduct(sc);

        controller.openList();
        controller.step1();
        System.assertEquals(controller.showProducts, true);

        Product__c newProduct = [SELECT Id FROM Product__c];
        controller.selectedProductId = newProduct.Id;
        controller.selectProduct();

        Product_Rate_Plan__c productRatePlan = [SELECT Id FROM Product_Rate_Plan__c];

        controller.selectedPlanId = productRatePlan.Id;
        controller.selectPlan();
        System.assertEquals(controller.showCharges, true);

        controller.selectedChargeId = productRatePlanCharge.Id;
        for (VTMig_AddOrderProduct.ProdCharge prodCharge : controller.prodCharges) {
            prodCharge.quantity = 1;
        }
        controller.selectCharge();
        System.assertEquals(controller.showChosenCharges, true);

        controller.step2();
        System.assertEquals(controller.pageStep, '2');


        Decimal total = controller.grandTotal;
        controller.overallDiscount = 10;
        controller.recalculate();
        System.assertNotEquals(controller.grandTotal, total);

        controller.removeChargeId = 0;
        controller.removeCharge();

        PageReference pageRef2 = controller.saveProducts();

        Test.stopTest();

    }

}