src/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>IITIntended_Use__c</fullName>
        <label>Intended Use</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Intended_Use</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal_Entity__c</fullName>
        <label>Legal Entity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Legal_Entity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Platform_or_Vessel_detail__c</fullName>
        <inlineHelpText>Select the specific platform or vessel category that is related to specific Titles.</inlineHelpText>
        <label>Vessel or Platform Detail</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Vessel_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipping_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipping Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary(Shipping) Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders (Shipping Contact)</relationshipLabel>
        <relationshipName>Job1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wet_or_Dry_Cargo__c</fullName>
        <inlineHelpText>If using a Full VOD, select Wet or Dry Cargo</inlineHelpText>
        <label>Wet or Dry Cargo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dry Cargo</fullName>
                </value>
                <value>
                    <fullName>Wet Cargo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order (InvoiceIT) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>IITIntended_Use__c</fullName>
        <label>Intended Use</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Intended_Use</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal_Entity__c</fullName>
        <label>Legal Entity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Legal_Entity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Platform_or_Vessel_Detail__c</fullName>
        <label>Platform or Vessel Detail</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Platform_Vessel_Detail</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipping_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipping Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>KV Platform</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Shipping_Account_Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary(Shipping) Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Shipping Contact)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wet_or_Dry_Cargo__c</fullName>
        <label>Wet or Dry Cargo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dry Cargo</fullName>
                </value>
                <value>
                    <fullName>Wet Cargo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity_Product__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice IT Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>Quote_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Product</label>
    <nameField>
        <label>Opportunity Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity_Rate_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Product__c</fullName>
        <label>Opportunity Product</label>
        <referenceTo>Opportunity_Product__c</referenceTo>
        <relationshipLabel>Opportunity Rate Plans</relationshipLabel>
        <relationshipName>Opportunity_Rate_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Rate Plan</label>
        <referenceTo>Product_Rate_Plan__c</referenceTo>
        <relationshipLabel>Opportunity Rate Plans</relationshipLabel>
        <relationshipName>Opportunity_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Rate Plan</label>
    <nameField>
        <label>Opportunity Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity_Rate_Plan_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Rate_Plan__c</fullName>
        <label>Opportunity Rate Plan</label>
        <referenceTo>Opportunity_Rate_Plan__c</referenceTo>
        <relationshipLabel>Opportunity Rate Plan Charges</relationshipLabel>
        <relationshipName>Opportunity_Rate_Plan_Charges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price_Type__c</fullName>
        <label>Price Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Price_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pricing_Model__c</fullName>
        <label>Pricing Model</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pricing_Model</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Charge_Category__c</fullName>
        <label>Product Charge Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Taxable</fullName>
                    <default>true</default>
                    <label>Taxable</label>
                </value>
                <value>
                    <fullName>Non Taxable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Rate Plan Charge</label>
        <referenceTo>Product_Rate_Plan_Charge__c</referenceTo>
        <relationshipLabel>Opportunity Rate Plan Charges</relationshipLabel>
        <relationshipName>Opportunity_Rate_Plan_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscription Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Title Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Of_Measurement__c</fullName>
        <label>UOM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>UOM</valueSetName>
        </valueSet>
    </fields>
    <label>Opportunity Rate Plan Charge</label>
    <nameField>
        <label>Opportunity Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Rate_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product Rate Plans</relationshipLabel>
        <relationshipName>Product_Rate_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Product Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Rate_Plan_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Price_Type__c</fullName>
        <description>This will specify whether price is onetime, weekly, monthly etc or usage(metered) based.</description>
        <label>Price Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One Time</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Half Yearly</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Usage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Charge_Category__c</fullName>
        <description>Use this field if you would want to configure different Tax or VAT percentages for different categories.</description>
        <inlineHelpText>Use this field if you would want to configure different Tax or VAT percentages for different categories.</inlineHelpText>
        <label>Tax Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Taxable</fullName>
                    <default>true</default>
                    <label>Taxable</label>
                </value>
                <value>
                    <fullName>Non Taxable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <label>Product Rate Plan</label>
        <referenceTo>Product_Rate_Plan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charges</relationshipLabel>
        <relationshipName>Product_Rate_Plan_Charges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subscription_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscription Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Title Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Of_Measurement__c</fullName>
        <description>Unit of measurement
(Unit, kilo, tonne etc)</description>
        <inlineHelpText>Unit of measurement
(Unit, kilo, tonne etc)</inlineHelpText>
        <label>UOM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>UOM</valueSetName>
        </valueSet>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Product Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Legal_Entity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>VMA</fullName>
    </customValue>
    <customValue>
        <fullName>VMI</fullName>
    </customValue>
    <customValue>
        <fullName>VCR</fullName>
        <isActive>false</isActive>
        <label>VCR</label>
    </customValue>
    <customValue>
        <fullName>VTS</fullName>
        <isActive>false</isActive>
        <label>VTS</label>
    </customValue>
    <masterLabel>Legal Entity</masterLabel>
</GlobalValueSet>

src/globalValueSets/Price_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>One Time</fullName>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Half Yearly</fullName>
    </customValue>
    <customValue>
        <fullName>Annual</fullName>
    </customValue>
    <customValue>
        <fullName>Usage</fullName>
    </customValue>
    <masterLabel>Price Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Vessel_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bulk Carrier</fullName>
    </customValue>
    <customValue>
        <fullName>Chemical Tanker</fullName>
    </customValue>
    <customValue>
        <fullName>Container</fullName>
    </customValue>
    <customValue>
        <fullName>Container Ship</fullName>
    </customValue>
    <customValue>
        <fullName>Crude Oil Tanker</fullName>
    </customValue>
    <customValue>
        <fullName>Crude Tanker</fullName>
    </customValue>
    <customValue>
        <fullName>Dry Cargo</fullName>
    </customValue>
    <customValue>
        <fullName>Gas Carrier</fullName>
    </customValue>
    <customValue>
        <fullName>General Cargo Vessel</fullName>
    </customValue>
    <customValue>
        <fullName>Heavy Lift Vessel</fullName>
    </customValue>
    <customValue>
        <fullName>LNG Carriers</fullName>
    </customValue>
    <customValue>
        <fullName>Misc</fullName>
    </customValue>
    <customValue>
        <fullName>Offshore</fullName>
    </customValue>
    <customValue>
        <fullName>Offshore Supply Vessel</fullName>
    </customValue>
    <customValue>
        <fullName>Passenger</fullName>
    </customValue>
    <customValue>
        <fullName>Product Oil Tanker</fullName>
    </customValue>
    <customValue>
        <fullName>Reefer</fullName>
    </customValue>
    <customValue>
        <fullName>RO-RO PCC</fullName>
    </customValue>
    <customValue>
        <fullName>Seismic Survey Vessels</fullName>
    </customValue>
    <customValue>
        <fullName>Tankers</fullName>
    </customValue>
    <customValue>
        <fullName>Tugs</fullName>
    </customValue>
    <masterLabel>Vessel Types</masterLabel>
</GlobalValueSet>

src/classes/VTMig_ProductSelection_Extension.cls
/**
 * Created by tricia on 10/24/2019.
 */

public with sharing class VTMig_ProductSelection_Extension {

    public Id OppId {get; set;}
    public Opportunity Opp {get; set;}
    public Job__c Order {get; set;}
    public String prodSearchText {get; set;}
    public List<Product__c> ProductList {get; set;}
    public String selectedProductId {get; set;}
    public String selectedPlanId {get; set;}
    public String selectedChargeId {get; set;}
    public String removeChargeId {get; set;}
    public Decimal overallDiscount {get;set;}
    public Decimal grandTotal {get;set;}
    public Product_Rate_Plan_Charge__c selectedCharge {get; set;}
    public List<Product_Rate_Plan__c> plans {get; set;}
    public List<ProdCharge> prodCharges {get; set;}
    public Boolean showProducts {get; set;}
    public Boolean showPlans {get; set;}
    public Boolean showCharges {get; set;}
    public Boolean showChosenCharges {get; set;}
    public String pageStep {get; set;}
    public List<OppCharge> selectedCharges {get;set;}
    public List<ProdCharge> selectedProdCharges {get;set;}

    public VTMig_ProductSelection_Extension(ApexPages.StandardController ctrlr){
        OppId = ApexPages.currentPage().getParameters().get('Id');
        selectedCharges = new List<OppCharge>();
        prodCharges = new List<ProdCharge>();
        ProductList = new List<Product__c>();
        selectedProdCharges = new List<ProdCharge>();
        showProducts = false;
        showPlans = false;
        showCharges = false;
        pageStep = '1';
        grandTotal = 0;
        Opp = [SELECT Name, AccountId, Wet_or_Dry_Cargo__c, Platform_or_Vessel_Detail__c, Shipping_Account__c, Shipping_Contact__c, Partner_Agent__c, IITIntended_Use__c, Legal_Entity__c FROM Opportunity WHERE Id = : OppId];
        List<Opportunity_Rate_Plan_Charge__c> currentCharges = [SELECT Id, Name, Product_Charge_Category__c, Subscription_Product__c, Opportunity_Rate_Plan__r.Opportunity_Product__r.Name,
                Opportunity_Rate_Plan__r.Opportunity_Product__r.Product__c, Product_Rate_Plan_Charge__c,
                Title_Product__c, Unit_Of_Measurement__c, Price_Type__c, Pricing_Model__c, Unit_Price__c,
                Quantity__c, Opportunity_Rate_Plan__r.Opportunity_Product__r.Product_Code__c, Opportunity_Rate_Plan__r.Product_Rate_Plan__c
        FROM Opportunity_Rate_Plan_Charge__c WHERE Opportunity__c = : OppId];
        if(currentCharges.size() > 0) {
            for(Opportunity_Rate_Plan_Charge__c currentCharge : currentCharges) {
                ProdCharge singleProdCharge = new ProdCharge();
                singleProdCharge.prodCharge = [SELECT Id, Name, Product_Charge_Category__c, Subscription_Product__c, Product_Rate_Plan__r.Product__r.Name,
                        Title_Product__c, Unit_Of_Measurement__c, Price_Type__c, Pricing_Format__c, Unit_Price__c, Product_Rate_Plan__r.Product__r.Product_Code__c
                FROM Product_Rate_Plan_Charge__c WHERE Id = : currentCharge.Product_Rate_Plan_Charge__c];
                singleProdCharge.quantity = Integer.valueOf(currentCharge.Quantity__c);
                singleProdCharge.planId = currentCharge.Opportunity_Rate_Plan__r.Product_Rate_Plan__c;
                singleProdCharge.prodId = currentCharge.Opportunity_Rate_Plan__r.Opportunity_Product__r.Product__c;
                selectedProdCharges.add(singleProdCharge);
            }
            showChosenCharges = true;
        } else {
            showChosenCharges = false;
        }
    }

    public void openList(){
        String activeStatus = 'Active';
        String query = 'SELECT Id, Name, Description__c, Effective_Period__c, External_ID__c, ' +
                'GL_Account_Receivable_Number__c, Manufacturer__c, Product_Code__c, Product_Family__c, ' +
                'Status__c, Unique_Identifier__c, Valid_From_Date__c, Valid_To_Date__c ' +
                'FROM Product__c WHERE Status__c = : activeStatus ';
        if(String.isNotEmpty(prodSearchText)){
            String prodSearch = '%' + prodSearchText + '%';
            query = query + 'AND Name LIKE : prodSearch';
        }
        ProductList = Database.query(query);
        showProducts = true;
        showPlans = false;
        showCharges = false;
    }

    public void selectProduct(){
        System.debug(selectedProductId);
        showProducts = false;
        showCharges = false;
        plans = [SELECT Id, Name, Description__c FROM Product_Rate_Plan__c WHERE Status__c = 'Active' AND Product__c = : selectedProductId];
        showPlans = true;
    }

    public void selectPlan(){
        showProducts = false;
        showPlans = false;
        List<Product_Rate_Plan_Charge__c> charges = [SELECT Id, Name, Product_Charge_Category__c, Subscription_Product__c, Product_Rate_Plan__r.Product__r.Name,
                Title_Product__c, Unit_Of_Measurement__c, Price_Type__c, Pricing_Format__c, Unit_Price__c, Quantity__c, Product_Rate_Plan__r.Product__r.Product_Code__c
        FROM Product_Rate_Plan_Charge__c WHERE Product_Rate_Plan__c = : selectedPlanId];
        for(Product_Rate_Plan_Charge__c charge : charges) {
            ProdCharge newProdCharge = new ProdCharge();
            newProdCharge.prodCharge = charge;
            newProdCharge.prodId = selectedProductId;
            newProdCharge.planId = selectedPlanId;
            prodCharges.add(newProdCharge);
        }
        showCharges = true;
    }

    public void selectCharge(){

        Integer quantity = 0;
        ProdCharge selectedProdCharge = new ProdCharge();
        for(ProdCharge prodCharge : prodCharges) {
            if(prodCharge.prodCharge.Id == selectedChargeId) {
                quantity = prodCharge.quantity;
                selectedProdCharge = prodCharge;
            }
        }
        selectedProdCharges.add(selectedProdCharge);
        prodSearchText = '';
        selectedChargeId = '';
        selectedPlanId = '';
        selectedProductId = '';
        plans.clear();
        prodCharges.clear();
        showCharges = false;
        showPlans = false;
        showProducts = false;
        showChosenCharges = true;
    }

    public void removeCharge(){

        for(Integer i = 0; i<selectedProdCharges.size(); i++) {
            if(removeChargeId == selectedProdCharges[i].prodCharge.Id) {
                selectedProdCharges.remove(i);
            }
        }
        removeChargeId = '';
    }

    public void step2(){

        for(ProdCharge selectedProdCharge : selectedProdCharges) {
            OppCharge currentCharge = new OppCharge();
            currentCharge.prodCharge = selectedProdCharge;
            currentCharge.opportunityProduct = configOppProd(selectedProdCharge.prodId);
            currentCharge.opportunityRatePlan = configOppPlan(selectedProdCharge.planId, currentCharge.opportunityProduct.Id);
            currentCharge.opportunityRatePlanCharge = configOppCharge(selectedProdCharge.prodCharge.Id, currentCharge.opportunityRatePlan.Id, selectedProdCharge.quantity);
            selectedCharges.add(currentCharge);
            grandTotal = grandTotal + currentCharge.opportunityRatePlanCharge.Price__c;
        }
        pageStep = '2';
    }

    public void step1(){
        selectedCharges.clear();
        pageStep = '1';
    }

    public PageReference saveProducts(){

        List<Opportunity_Product__c> oppProducts = new List<Opportunity_Product__c>();
        List<Opportunity_Rate_Plan__c> oppRatePlans = new List<Opportunity_Rate_Plan__c>();
        List<Opportunity_Rate_Plan_Charge__c> oppCharges = new List<Opportunity_Rate_Plan_Charge__c>();
        for(OppCharge opportunityCharge : selectedCharges) {
            oppProducts.add(opportunityCharge.opportunityProduct);
        }
        insert oppProducts;
        for(OppCharge opportunityCharge : selectedCharges) {
            Id oppProdId;
            for(Opportunity_Product__c oppProduct : oppProducts) {
                if(oppProduct.Product__c == opportunityCharge.prodCharge.prodId){
                    oppProdId = oppProduct.Id;
                }
            }
            Opportunity_Rate_Plan__c oppRatePlan = configOppPlan(opportunityCharge.prodCharge.planId, oppProdId);
            oppRatePlans.add(oppRatePlan);
        }
        insert oppRatePlans;
        Decimal runningTotal = 0;
        for(OppCharge opportunityCharge : selectedCharges) {
            Id ratePlanId;
            for(Opportunity_Rate_Plan__c oppRatePlan : oppRatePlans) {
                if(oppRatePlan.Product_Rate_Plan__c == opportunityCharge.prodCharge.planId) {
                    ratePlanId = oppRatePlan.Id;
                }
            }
            runningTotal = runningTotal + opportunityCharge.opportunityRatePlanCharge.Unit_Price__c * opportunityCharge.opportunityRatePlanCharge.Quantity__c;
            Opportunity_Rate_Plan_Charge__c oppRatePlanCharge = configOppCharge(opportunityCharge.prodCharge.prodCharge.Id, ratePlanId, opportunityCharge.prodCharge.quantity);
            oppCharges.add(oppRatePlanCharge);
        }
        insert oppCharges;
        Opp.Discount_Value__c = runningTotal - grandTotal;
        Opp.Amount = grandTotal;
        update Opp;
        PageReference pageRef = new PageReference('/'+OppId);
        return pageRef;
    }

    public Opportunity_Rate_Plan__c configOppPlan(String planId, String oppProdId) {

        Product_Rate_Plan__c ratePlan = [SELECT Id, Name, Description__c, Sequence_Number__c FROM Product_Rate_Plan__c WHERE Id =: planId];
        Opportunity_Rate_Plan__c opportunityRatePlan = new Opportunity_Rate_Plan__c();
        opportunityRatePlan.Name = ratePlan.Name;
        opportunityRatePlan.Product_Rate_Plan__c = ratePlan.Id;
        opportunityRatePlan.Description__c = ratePlan.Description__c;
        opportunityRatePlan.SequenceNumber__c = ratePlan.Sequence_Number__c;
        opportunityRatePlan.Opportunity_Product__c = oppProdId;
        return opportunityRatePlan;
    }

    public Opportunity_Product__c configOppProd(String prodId) {

        Product__c chosenProduct = [SELECT Id, Description__c, Product_Code__c, Product_Family__c, Name FROM Product__c WHERE Id =: prodId];
        Opportunity_Product__c oppProduct = new Opportunity_Product__c();
        oppProduct.Name = chosenProduct.Name;
        oppProduct.Description__c = chosenProduct.Description__c;
        oppProduct.Product__c = prodId;
        oppProduct.Product_Family__c = chosenProduct.Product_Family__c;
        oppProduct.Product_Code__c = chosenProduct.Product_Code__c;
        oppProduct.Opportunity__c = OppId;
        return oppProduct;
    }

    public Opportunity_Rate_Plan_Charge__c configOppCharge(String chargeId, String planId, Integer quantityInteger) {
        Product_Rate_Plan_Charge__c charge = [SELECT Id, Name, Product_Charge_Category__c, Subscription_Product__c,
                Title_Product__c, Unit_Of_Measurement__c, Price_Type__c, Pricing_Format__c, Unit_Price__c
        FROM Product_Rate_Plan_Charge__c WHERE Id =: chargeId];
        Opportunity_Rate_Plan_Charge__c newCharge = new Opportunity_Rate_Plan_Charge__c();
        newCharge.Name = charge.Name;
        newCharge.Product_Charge_Category__c = charge.Product_Charge_Category__c;
        newCharge.Subscription_Product__c = charge.Subscription_Product__c;
        newCharge.Title_Product__c = charge.Title_Product__c;
        newCharge.Unit_Of_Measurement__c = charge.Unit_Of_Measurement__c;
        newCharge.Price_Type__c = charge.Price_Type__c;
        newCharge.Pricing_Model__c = charge.Pricing_Format__c;
        newCharge.Unit_Price__c = charge.Unit_Price__c;
        newCharge.External_Id__c = selectedPlanId;
        newCharge.Product_Rate_Plan_Charge__c = charge.Id;
        newCharge.Quantity__c = quantityInteger;
        newCharge.Opportunity_Rate_Plan__c = planId;
        newCharge.Price__c = charge.Unit_Price__c * quantityInteger;
        newCharge.Discount_Percent__c = 0.00;
        newCharge.Opportunity__c = OppId;
        return newCharge;
    }

    public void recalculate(){

        grandTotal = 0;
        for(OppCharge selectedCharge: selectedCharges) {
            selectedCharge.opportunityRatePlanCharge.Price__c = selectedCharge.opportunityRatePlanCharge.Unit_Price__c * selectedCharge.opportunityRatePlanCharge.Quantity__c * (1-(selectedCharge.opportunityRatePlanCharge.Discount_Percent__c/100));
            selectedCharge.opportunityRatePlanCharge.Discount_Value__c = selectedCharge.opportunityRatePlanCharge.Unit_Price__c * selectedCharge.opportunityRatePlanCharge.Quantity__c - selectedCharge.opportunityRatePlanCharge.Price__c;
            grandTotal = grandTotal + selectedCharge.opportunityRatePlanCharge.Price__c;
        }
        if(overallDiscount > 0) {
            grandTotal = grandTotal * (1-(overallDiscount/100));
        }

    }

    public class OppCharge{
        public ProdCharge prodCharge {get;set;}
        public Opportunity_Rate_Plan__c opportunityRatePlan {get;set;}
        public Opportunity_Product__c opportunityProduct {get;set;}
        public Opportunity_Rate_Plan_Charge__c opportunityRatePlanCharge {get;set;}

        public OppCharge(){}
    }

    public class ProdCharge{
        public Product_Rate_Plan_Charge__c prodCharge {get;set;}
        public Integer quantity {get;set;}
        public String prodId {get;set;}
        public String planId {get;set;}

        public ProdCharge(){}
    }
}