src/objects/Order_Commissions__c.object
<CustomObject>
    <description>This object is defined to identify the Agents that are to receive commission for a specific order based on the Product and the standard or adjusted commission rates.</description>
    <fields>
        <fullName>Commission_Basis__c</fullName>
        <inlineHelpText>Most Rental commissions based at the Master Order Level. Some Custom / Split  commissions based on the Child Order. If this commission is based specifically on the individual child order, please select Child Order, and Edit the Child Order.</inlineHelpText>
        <label>Commission Basis</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Master Order</fullName>
                    <default>true</default>
                    <label>Master Order</label>
                </value>
                <value>
                    <fullName>Child Order</fullName>
                </value>
                <value>
                    <fullName>Sale Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Custom_Order_Commissions__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check if this partner is scheduled for custom commissions for this order.</inlineHelpText>
        <label>Custom Order Commissions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Master_OrderID__c</fullName>
        <formula>CASESAFEID(Order_for_Commission__r.Master_Order__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Master OrderID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Order Commissions</relationshipLabel>
        <relationshipName>Order_Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_for_Commission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the Applicable Order to be commissioned</inlineHelpText>
        <label>Order for Commission</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Order Commissions</relationshipLabel>
        <relationshipName>Order_Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Agent__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Select a KV Partner Account as the Sales Agent.</inlineHelpText>
        <label>Sales Agent</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select an appropriate Partner Account.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>KV Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Commissions</relationshipLabel>
        <relationshipName>Order_Commissions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subsequent_Years_Commission_Rate__c</fullName>
        <inlineHelpText>Enter the Commission Rate for Subsequent Years</inlineHelpText>
        <label>Subsequent Years Commission Rate</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Year1_Commission__c</fullName>
        <inlineHelpText>Select the First Year Commission Rate for this order</inlineHelpText>
        <label>Year1 Commission</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Order Commissions</label>
    <nameField>
        <displayFormat>OCOM-{0000}</displayFormat>
        <label>Commissionable Agents Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Partner_Commission_Rates__c.object
<CustomObject>
    <description>This custom object allow users to create records to define stand commission rates that are based on a Type of Commission and related to Products (InvoiceIT)</description>
    <fields>
        <fullName>Partner_Agent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the Partner / Sales Agent</inlineHelpText>
        <label>Partner / Agent Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>KV Partner</value>
            </filterItems>
            <infoMessage>This currently looks up to KV Partners. The value entered does not exist or does not match filter criteria. Remove filter criteria to search all accounts.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Commission Rates</relationshipLabel>
        <relationshipName>Partner_Commission_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This looks up to the InvoiceIT Product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Partner Commission Rates</relationshipLabel>
        <relationshipName>Partner_Commission_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard_Comm__c</fullName>
        <inlineHelpText>Enter the standard commission for this Partner Agent for the selected Product for all subsequent years after year 1</inlineHelpText>
        <label>Standard Comm (after Yr1)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Year1_Commission__c</fullName>
        <inlineHelpText>Commission for Year 1. This is specific to Rentals and Subscriptions</inlineHelpText>
        <label>Year1 Commission</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Partner Commission Rates</label>
    <nameField>
        <displayFormat>PCR-{0000}</displayFormat>
        <label>Partner Commission Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Commission Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <label>Invoice IT Product</label>
    <nameField>
        <label>InvoiceIT Product  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice IT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderCommisionTriggerHandlerClass.cls
/* ************************************************************
 * Created By  : Gopi Kishore
 * Created Date:  
 * Description : OrderCommisionTriggerHandlerClass Used to implement following functionlality from OrderCommisionTrigger trigger.
                 1) populating commision order values from partner commission rate object.
 *               2) validating if order master commision salesagenss
                 
 * Modified By   :
 * Modified Date : 
 * Description   :
 * 
 * ************************************************************/

Public Class OrderCommisionTriggerHandlerClass{
    
    Public Static void AutoPopulateCommisionValues(List<Order_Commissions__c> ocListData,Map<Id,Order_Commissions__c> ocNewMapData,Map<Id,Order_Commissions__c> ocOldMapData,String DMLOperation){
        
        Set<ID> accIds = New Set<ID>();
        Set<String> validateMasterOrdersCommisions = New Set<String>(); 
        Set<String> avoidOrderCommissionAgentDupes = New Set<String>();
        
        
        for(Order_Commissions__c orderCommision:ocListData){
            if(!orderCommision.Custom_Order_Commissions__c){
                accIds.add(orderCommision.Sales_Agent__c);
            }
            if(orderCommision.Commission_Basis__c == 'Master Order'){
                validateMasterOrdersCommisions.add(orderCommision.Master_OrderID__c);
            }
            if(DMLOperation=='Insert'){
                validateMasterOrdersCommisions.add(orderCommision.Order_for_Commission__c);
            }
        }
        
        Map<ID,Set<ID>> masterSalesAgents = New Map<ID,Set<ID>>();
        List<Order_Commissions__c> masterOrderSalesAgents = [SELECT ID,Master_OrderID__c,Sales_Agent__c,Order_for_Commission__c,Order_Product__c FROM Order_Commissions__c where (Order_for_Commission__c=:validateMasterOrdersCommisions AND Order_for_Commission__c!=null)];
        
        for(Order_Commissions__c orderAgents:masterOrderSalesAgents){
            if(validateMasterOrdersCommisions.contains(orderAgents.Master_OrderID__c)){
                if(masterSalesAgents.containsKey(orderAgents.Order_for_Commission__c)) {
                    Set<Id> masterAgentsSet = masterSalesAgents.get(orderAgents.Order_for_Commission__c);
                    masterAgentsSet.add(orderAgents.Sales_Agent__c);
                    masterSalesAgents.put(orderAgents.Order_for_Commission__c, masterAgentsSet);
                } else {
                    masterSalesAgents.put(orderAgents.Order_for_Commission__c, new Set<Id> {orderAgents.Sales_Agent__c});
                }
            }
            if(orderAgents.Order_for_Commission__c!=null && orderAgents.Sales_Agent__c!=null && orderAgents.Order_Product__c!=null && DMLOperation=='Insert'){
                avoidOrderCommissionAgentDupes.add(orderAgents.Order_for_Commission__c+'-'+orderAgents.Sales_Agent__c+'-'+orderAgents.Order_Product__c);
            }
        }
        
        
        Map<String,Partner_Commission_Rates__c> partnerCommisionRates = New Map<String,Partner_Commission_Rates__c>();
        
        List<Partner_Commission_Rates__c> pcr = [SELECT ID,Partner_Agent_Account__c,Product__c,Standard_Comm__c,Year1_Commission__c FROM Partner_Commission_Rates__c where Partner_Agent_Account__c=:accIds];
        
        for(Partner_Commission_Rates__c productAgents:pcr){
            partnerCommisionRates.put(productAgents.Product__c+'-'+productAgents.Partner_Agent_Account__c,productAgents);
        }
        
        for(Order_Commissions__c orderCommision:ocListData){ 
            System.Debug('=====>'+avoidOrderCommissionAgentDupes);
            System.Debug('=====>'+orderCommision.Order_for_Commission__c+'-'+orderCommision.Sales_Agent__c+'-'+orderCommision.Order_Product__c);
            if(!avoidOrderCommissionAgentDupes.Contains(orderCommision.Order_for_Commission__c+'-'+orderCommision.Sales_Agent__c+'-'+orderCommision.Order_Product__c)){
                if(!orderCommision.Custom_Order_Commissions__c){
                    if(orderCommision.Commission_Basis__c == 'Master Order' && masterSalesAgents.ContainsKey(orderCommision.Master_OrderID__c)){
                        Set<ID> masterAgentsData = masterSalesAgents.get(orderCommision.Master_OrderID__c);
                        if(!masterAgentsData.contains(orderCommision.Sales_Agent__c)){
                            orderCommision.addError('There is no Master Order - Order Commission for this Sales Agent / Partner. Please add a Master Order - Order Commission, or change the Child Order - Order Commission > Commission Basis to "Child Order"');
                        }
                    }
                    String reorder = orderCommision.Order_Product__c+'-'+orderCommision.Sales_Agent__c;
                    if(partnerCommisionRates.containsKey(reorder)){
                        orderCommision.Subsequent_Years_Commission_Rate__c = partnerCommisionRates.get(reorder).Standard_Comm__c;
                        orderCommision.Year1_Commission__c = partnerCommisionRates.get(reorder).Year1_Commission__c;
                    }
                }
            }else{
                orderCommision.addError('This partner already has an order commission for the product. Please validate the current order commission.');
            }
        }  
    } 
}